<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class BipotnamaSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'bipot_nama_id' => '18',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '18',
                'nama' => 'Pindah Kelas/Prog/Jur',
                'singkatan' => 'KPJ',
                'trx_id' => '1',
                'baris' => '18',
                'detil' => 'N',
                'def_jumlah' => '150000',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '1',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '1',
                'nama' => 'Pendaftaran',
                'singkatan' => 'PDF',
                'trx_id' => '1',
                'baris' => '1',
                'detil' => 'Y',
                'def_jumlah' => '75000',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '2',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '2',
                'nama' => 'Sarana Pendidikan',
                'singkatan' => 'SP',
                'trx_id' => '1',
                'baris' => '2',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '3',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '3',
                'nama' => 'Bimbingan Akademik',
                'singkatan' => 'BA',
                'trx_id' => '1',
                'baris' => '3',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '4',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '4',
                'nama' => 'Kuliah Umum & BAKSOS',
                'singkatan' => 'KUB',
                'trx_id' => '1',
                'baris' => '4',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'Y',
                'pb' => 'N',
                'id_legacy' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '5',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '5',
                'nama' => 'Jaket Alamamater & Dasi',
                'singkatan' => 'JAD',
                'trx_id' => '1',
                'baris' => '5',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '6',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '6',
                'nama' => 'SPP & Pengembangan',
                'singkatan' => 'SPP',
                'trx_id' => '1',
                'baris' => '6',
                'detil' => 'Y',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '7',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '7',
                'nama' => 'Proyek TA',
                'singkatan' => 'PTA',
                'trx_id' => '1',
                'baris' => '7',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '8',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '8',
                'nama' => 'KPL (Kuliah Pengenalan Lapangan)',
                'singkatan' => 'KPL',
                'trx_id' => '1',
                'baris' => '8',
                'detil' => 'Y',
                'def_jumlah' => '1',
                'def_besar' => '750000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '9',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '9',
                'nama' => 'Bimbingan',
                'singkatan' => 'BIM',
                'trx_id' => '1',
                'baris' => '9',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '10',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '10',
                'nama' => 'Wisuda',
                'singkatan' => 'WSD',
                'trx_id' => '1',
                'baris' => '10',
                'detil' => 'Y',
                'def_jumlah' => '1',
                'def_besar' => '1500000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '11',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '11',
                'nama' => 'Sidang',
                'singkatan' => 'SDG',
                'trx_id' => '1',
                'baris' => '11',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '12',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '12',
                'nama' => 'Daftar Remedial',
                'singkatan' => 'RMD',
                'trx_id' => '1',
                'baris' => '12',
                'detil' => 'Y',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '13',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '13',
                'nama' => 'Cuti',
                'singkatan' => 'CT',
                'trx_id' => '1',
                'baris' => '13',
                'detil' => 'Y',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '14',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '14',
                'nama' => 'Konversi',
                'singkatan' => 'KVS',
                'trx_id' => '1',
                'baris' => '14',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '15',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '15',
                'nama' => 'Pindah',
                'singkatan' => 'PDH',
                'trx_id' => '1',
                'baris' => '15',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'Y',
                'pb' => 'N',
                'id_legacy' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '16',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '16',
                'nama' => 'Perpanjang Masa Studi',
                'singkatan' => 'PMS',
                'trx_id' => '1',
                'baris' => '16',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '17',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '17',
                'nama' => 'SKS',
                'singkatan' => 'SKS',
                'trx_id' => '1',
                'baris' => '17',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'Y',
                'pb' => 'N',
                'id_legacy' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '19',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '1',
                'nama' => 'MGS',
                'singkatan' => 'MGS',
                'trx_id' => '-1',
                'baris' => '19',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '20',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '2',
                'nama' => 'Beasiswa',
                'singkatan' => 'BSW',
                'trx_id' => '-1',
                'baris' => '20',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '24',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '3',
                'nama' => 'Prakuliah (Bimb. Akad, Baksos,Jaket, Attribut)',
                'singkatan' => 'PRA',
                'trx_id' => '1',
                'baris' => '3',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '25',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '14',
                'nama' => 'Permatakuliah',
                'singkatan' => 'PMK',
                'trx_id' => '1',
                'baris' => '8',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '26',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '19',
                'nama' => 'Sumbangan Kurban',
                'singkatan' => 'SK',
                'trx_id' => '1',
                'baris' => '19',
                'detil' => 'Y',
                'def_jumlah' => '20000',
                'def_besar' => '20000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '27',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '4',
                'nama' => 'Biaya Penyelenggaraan Pendidikan',
                'singkatan' => 'BPP',
                'trx_id' => '1',
                'baris' => '4',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'Y',
                'pb' => 'N',
                'id_legacy' => '27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '30',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '2',
                'nama' => 'Registrasi Kelas Shift',
                'singkatan' => 'RKS',
                'trx_id' => '1',
                'baris' => '4',
                'detil' => 'N',
                'def_jumlah' => '200000',
                'def_besar' => '200000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'Y',
                'pb' => 'N',
                'id_legacy' => '30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '28',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '2',
                'nama' => 'Bimbingan Akademik & BAKSOS',
                'singkatan' => 'BAB',
                'trx_id' => '1',
                'baris' => '2',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '50000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'Y',
                'pb' => 'N',
                'id_legacy' => '28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '29',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '3',
                'nama' => 'Bakti Sosial',
                'singkatan' => 'BS',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'Y',
                'def_jumlah' => '1',
                'def_besar' => '350000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '31',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '20',
                'nama' => 'UTS (Ujian Tengah Semester)',
                'singkatan' => 'UTS',
                'trx_id' => '1',
                'baris' => '11',
                'detil' => 'N',
                'def_jumlah' => '1',
                'def_besar' => '50000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '32',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '21',
                'nama' => 'UAS (Ujian Akhir  Semester)',
                'singkatan' => 'UAS',
                'trx_id' => '1',
                'baris' => '11',
                'detil' => 'N',
                'def_jumlah' => '1',
                'def_besar' => '50000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '32',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '33',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '2',
                'nama' => 'MPLK, Baksos, Jaket, Atribut',
                'singkatan' => 'MPLK',
                'trx_id' => '1',
                'baris' => '2',
                'detil' => 'Y',
                'def_jumlah' => '1',
                'def_besar' => '600000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'Y',
                'pb' => 'N',
                'id_legacy' => '33',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '0',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '0',
                'nama' => 'Biaya Khusus',
                'singkatan' => 'BK',
                'trx_id' => '1',
                'baris' => '1',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '0',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '35',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '22',
                'nama' => 'HER',
                'singkatan' => 'HER',
                'trx_id' => '1',
                'baris' => '1',
                'detil' => 'Y',
                'def_jumlah' => '75000',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '35',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '36',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '23',
                'nama' => 'Seminar',
                'singkatan' => 'SMNR',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'Y',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '37',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '24',
                'nama' => 'Ganti Buku',
                'singkatan' => 'GB',
                'trx_id' => '1',
                'baris' => '1',
                'detil' => 'Y',
                'def_jumlah' => '1',
                'def_besar' => '50000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '37',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '38',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '4',
                'nama' => 'Dana Pokok Pendidikan',
                'singkatan' => 'DPP',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'Y',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'Y',
                'pb' => 'N',
                'id_legacy' => '38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '39',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '1',
                'nama' => 'Registrasi Awal Semester',
                'singkatan' => 'RAS',
                'trx_id' => '1',
                'baris' => '1',
                'detil' => 'Y',
                'def_jumlah' => '350000',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '39',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '40',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '25',
                'nama' => 'Hard Cover',
                'singkatan' => 'HC',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'Y',
                'def_jumlah' => '3',
                'def_besar' => '30000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '40',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '41',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '26',
                'nama' => 'Foto',
                'singkatan' => 'FT',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'Y',
                'def_jumlah' => '1',
                'def_besar' => '20000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '41',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '42',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '27',
                'nama' => 'Administrasi',
                'singkatan' => 'ADM',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'Y',
                'def_jumlah' => '2500',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'Y',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'Y',
                'pb' => 'N',
                'id_legacy' => '42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '43',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '28',
                'nama' => 'Kartu Mahasiswa',
                'singkatan' => 'KM',
                'trx_id' => '1',
                'baris' => '1',
                'detil' => 'Y',
                'def_jumlah' => '1',
                'def_besar' => '15000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '44',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '29',
                'nama' => 'TOEFL',
                'singkatan' => 'TOEFL',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '45',
                'kode_id' => 'PI',
                'rekening_id' => '8850000396',
                'urutan' => '0',
                'nama' => 'Potongan(Discount)',
                'singkatan' => 'POT',
                'trx_id' => '-1',
                'baris' => '1',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '46',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '13',
                'nama' => 'Administrasi Non Aktif',
                'singkatan' => 'NA',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'Y',
                'def_jumlah' => '1',
                'def_besar' => '200000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '47',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '13',
                'nama' => 'Administrasi Ijazah',
                'singkatan' => 'IJZ',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'N',
                'def_jumlah' => '1',
                'def_besar' => '50000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '48',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '0',
                'nama' => 'Status Mahasiswa',
                'singkatan' => 'STS',
                'trx_id' => '1',
                'baris' => '1',
                'detil' => 'Y',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'Y',
                'pb' => 'N',
                'id_legacy' => '48',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '49',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '9',
                'nama' => 'Seminar Proposal',
                'singkatan' => 'SPRO',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'N',
                'def_jumlah' => '1',
                'def_besar' => '165000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '50',
                'kode_id' => 'PI',
                'rekening_id' => null,
                'urutan' => '1',
                'nama' => 'Jaket + PKKMB + Sardik',
                'singkatan' => 'JPS',
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '250000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => null,
                'na' => 'N',
                'pb' => 'N',
                'id_legacy' => '50',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '52',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '30',
                'nama' => 'Legalisir Ijazah',
                'singkatan' => null,
                'trx_id' => '1',
                'baris' => '1',
                'detil' => 'Y',
                'def_jumlah' => '50000',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '52',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '53',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '9',
                'nama' => 'Perpajangan Bimbingan',
                'singkatan' => null,
                'trx_id' => '1',
                'baris' => '9',
                'detil' => 'N',
                'def_jumlah' => '0',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'Y',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '53',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '54',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '31',
                'nama' => 'Kartu Anggota Perpustakaan',
                'singkatan' => null,
                'trx_id' => '1',
                'baris' => '1',
                'detil' => 'Y',
                'def_jumlah' => '1',
                'def_besar' => '50000',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '54',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'bipot_nama_id' => '55',
                'kode_id' => 'PI',
                'rekening_id' => '',
                'urutan' => '32',
                'nama' => 'Kemah',
                'singkatan' => null,
                'trx_id' => '1',
                'baris' => '0',
                'detil' => 'N',
                'def_jumlah' => '100000',
                'def_besar' => '0',
                'diskon' => 'N',
                'kena_denda' => 'N',
                'dipotong_beasiswa' => 'N',
                'catatan' => '',
                'na' => 'N',
                'pb' => 'Y',
                'id_legacy' => '55',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Kosongkan tabel sebelum insert
        DB::table('m_bipotnama')->truncate();
        
        // Chunk insert untuk performa
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('m_bipotnama')->insert($chunk);
        }
    }
}