<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JabatanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'jabatan_id' => '10',
                'kode_jabatan' => 'K',
                'fakultas_id' => 'STMIK',
                'nama' => 'Ketua',
                'nama__en' => 'Chairman',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:22:53',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '11',
                'kode_jabatan' => 'PK1',
                'fakultas_id' => 'STMIK',
                'nama' => 'Puket Bidang Akademik',
                'nama__en' => 'Vice Chairman 1 of Academic Affairs',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:22:47',
                'def' => 'Y',
                'na' => 'N',
                'id_legacy' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '12',
                'kode_jabatan' => 'PK2',
                'fakultas_id' => 'STMIK',
                'nama' => 'Puket Bidang Adm dan Keuangan ',
                'nama__en' => 'Vice Chairman 2 of Administration',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:22:51',
                'def' => '',
                'na' => 'N',
                'id_legacy' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '13',
                'kode_jabatan' => 'PK3',
                'fakultas_id' => 'STMIK',
                'nama' => 'Puket Bidang Kemahasiswaan',
                'nama__en' => 'Vice Chairman 2 of Student Affairs',
                'jenis' => '1',
                'login_buat' => '120101110001',
                'tanggal_buat' => null,
                'tgl_buat' => '2012-12-03',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:23:12',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '14',
                'kode_jabatan' => 'PK4',
                'fakultas_id' => 'STMIK',
                'nama' => 'Puket Bidang Pemasaran',
                'nama__en' => 'Vice Chairman 2 of Marketing and Promotion',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:23:38',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '15',
                'kode_jabatan' => 'KK',
                'fakultas_id' => 'STMIK',
                'nama' => 'Koordinator Kampus',
                'nama__en' => 'Campus Coordinator',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:23:57',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '16',
                'kode_jabatan' => 'KUPT',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaBag Unit Penunjang Teknis',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:06:50',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '17',
                'kode_jabatan' => 'KBAAK',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaBag Biro Adm Akademik dan Kemahasiswaan',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:06:51',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '18',
                'kode_jabatan' => 'KBAU',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaBag Biro Adm Umum',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:06:53',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '19',
                'kode_jabatan' => 'KP2M',
                'fakultas_id' => 'STMIK',
                'nama' => 'Kepala P2M',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:06:54',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '20',
                'kode_jabatan' => 'KJ',
                'fakultas_id' => 'STMIK',
                'nama' => 'Ketua Jurusan',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:06:57',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '21',
                'kode_jabatan' => 'KsPs',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Perpustakaan',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:06',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '22',
                'kode_jabatan' => 'KsT',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Teknis',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:07',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '23',
                'kode_jabatan' => 'KsL',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Laboratorium',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:08',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '24',
                'kode_jabatan' => 'KsP',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Kepegawaian',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:08',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '25',
                'kode_jabatan' => 'Ksk',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Keuangan',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:09',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '26',
                'kode_jabatan' => 'KsKRT',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Kerumahtanggan',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:11',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '27',
                'kode_jabatan' => 'KsTU',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Tata Usaha',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:13',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '28',
                'kode_jabatan' => 'KsRS',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Registrasi dan Statistik',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:14',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '29',
                'kode_jabatan' => 'KsUS',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Ujian dan Sertifikasi',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:16',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '30',
                'kode_jabatan' => 'KsHA',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Humas dan Alumni',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:17',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '31',
                'kode_jabatan' => 'KsPM',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Pembinaan dan Mahasiswa',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:19',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '32',
                'kode_jabatan' => 'KsPP',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Penelitian dan Pengembangan ',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:21',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '32',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '33',
                'kode_jabatan' => 'KsPMs',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaSi Pengabdian Masyarakat',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '33',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '34',
                'kode_jabatan' => 'KIT',
                'fakultas_id' => 'STMIK',
                'nama' => 'KaBag Informasi dan Teknologi',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:27',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '34',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '1',
                'kode_jabatan' => 'KBP',
                'fakultas_id' => 'STMIK',
                'nama' => 'Ketua Badan Pendiri',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:05:23',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '2',
                'kode_jabatan' => 'KY',
                'fakultas_id' => 'YMII',
                'nama' => 'Ketua Yayasan',
                'nama__en' => '',
                'jenis' => '2',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2014-01-27 19:07:41',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '3',
                'kode_jabatan' => 'SY',
                'fakultas_id' => 'YMII',
                'nama' => 'Sekretaris Yayasan',
                'nama__en' => '',
                'jenis' => '2',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2014-01-27 19:07:46',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '4',
                'kode_jabatan' => 'BY',
                'fakultas_id' => 'YMII',
                'nama' => 'Bendahara Yayasan',
                'nama__en' => '',
                'jenis' => '2',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2014-01-27 19:07:47',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '5',
                'kode_jabatan' => 'BAUY',
                'fakultas_id' => 'YMII',
                'nama' => 'Bidang Adm Umum Yayasan',
                'nama__en' => '',
                'jenis' => '2',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2014-01-27 19:07:47',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '6',
                'kode_jabatan' => 'BAY',
                'fakultas_id' => 'YMII',
                'nama' => 'Bidang Akademik Yayasan',
                'nama__en' => '',
                'jenis' => '2',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2014-01-27 19:07:48',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '7',
                'kode_jabatan' => 'BKY',
                'fakultas_id' => 'YMII',
                'nama' => 'Bidang Kemahasiswaan Yayasan',
                'nama__en' => '',
                'jenis' => '2',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2014-01-27 19:07:49',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '8',
                'kode_jabatan' => 'BMY',
                'fakultas_id' => 'YMII',
                'nama' => 'Bidang Marketing Yayasan',
                'nama__en' => '',
                'jenis' => '2',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2014-01-27 19:07:52',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '9',
                'kode_jabatan' => 'LPUY',
                'fakultas_id' => 'YMII',
                'nama' => 'Bidang Litbang dan Bagus',
                'nama__en' => '',
                'jenis' => '2',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2014-01-27 19:07:55',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '35',
                'kode_jabatan' => 'K',
                'fakultas_id' => 'STBA',
                'nama' => 'Ketua',
                'nama__en' => 'Chairman',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:24:12',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '35',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '36',
                'kode_jabatan' => 'PK1',
                'fakultas_id' => 'STBA',
                'nama' => 'Puket Bidang Akademik',
                'nama__en' => 'Vice Chairman 1 of Academic Affairs',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:24:24',
                'def' => 'Y',
                'na' => 'N',
                'id_legacy' => '36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '37',
                'kode_jabatan' => 'PK2',
                'fakultas_id' => 'STBA',
                'nama' => 'Puket Bidang Adm dan Keuangan ',
                'nama__en' => 'Vice Chairman 2 of Administration',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:24:27',
                'def' => '',
                'na' => 'N',
                'id_legacy' => '37',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '38',
                'kode_jabatan' => 'PK3',
                'fakultas_id' => 'STBA',
                'nama' => 'Puket Bidang Kemahasiswaan',
                'nama__en' => 'Vice Chairman 2 of Student Affairs',
                'jenis' => '1',
                'login_buat' => '120101110001',
                'tanggal_buat' => null,
                'tgl_buat' => '2012-12-03',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:24:30',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '39',
                'kode_jabatan' => 'PK4',
                'fakultas_id' => 'STBA',
                'nama' => 'Puket Bidang Pemasaran',
                'nama__en' => 'Vice Chairman 2 of Marketing and Promotion',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-01-25 14:24:33',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '39',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '40',
                'kode_jabatan' => 'KK',
                'fakultas_id' => 'STBA',
                'nama' => 'Koordinator Kampus',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:42',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '40',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '41',
                'kode_jabatan' => 'KUPT',
                'fakultas_id' => 'STBA',
                'nama' => 'KaBag Unit Penunjang Teknis',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:07:59',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '41',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '42',
                'kode_jabatan' => 'KBAAK',
                'fakultas_id' => 'STBA',
                'nama' => 'KaBag Biro Adm Akademik dan Kemahasiswaan',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:00',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '43',
                'kode_jabatan' => 'KBAU',
                'fakultas_id' => 'STBA',
                'nama' => 'KaBag Biro Adm Umum',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:02',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '44',
                'kode_jabatan' => 'KP2M',
                'fakultas_id' => 'STBA',
                'nama' => 'Kepala P2M',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:03',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '45',
                'kode_jabatan' => 'KJ',
                'fakultas_id' => 'STBA',
                'nama' => 'Ketua Jurusan',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:04',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '46',
                'kode_jabatan' => 'KsPs',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Perpustakaan',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:12',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '47',
                'kode_jabatan' => 'KsT',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Teknis',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:12',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '48',
                'kode_jabatan' => 'KsL',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Laboratorium',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:13',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '48',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '49',
                'kode_jabatan' => 'KsP',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Kepegawaian',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:14',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '50',
                'kode_jabatan' => 'Ksk',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Keuangan',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:15',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '50',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '51',
                'kode_jabatan' => 'KsKRT',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Kerumahtanggan',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:15',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '51',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '52',
                'kode_jabatan' => 'KsTU',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Tata Usaha',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:17',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '52',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '53',
                'kode_jabatan' => 'KsRS',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Registrasi dan Statistik',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:18',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '53',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '54',
                'kode_jabatan' => 'KsUS',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Ujian dan Sertifikasi',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:19',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '54',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '55',
                'kode_jabatan' => 'KsHA',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Humas dan Alumni',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:19',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '55',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '56',
                'kode_jabatan' => 'KsPM',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Pembinaan dan Mahasiswa',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:20',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '56',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '57',
                'kode_jabatan' => 'KsPP',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Penelitian dan Pengembangan ',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:21',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '57',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '58',
                'kode_jabatan' => 'KsPMs',
                'fakultas_id' => 'STBA',
                'nama' => 'KaSi Pengabdian Masyarakat',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:23',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '58',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '59',
                'kode_jabatan' => 'KIT',
                'fakultas_id' => 'STBA',
                'nama' => 'KaBag Informasi dan Teknologi',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2012-12-10 13:08:25',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '59',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '60',
                'kode_jabatan' => 'K',
                'fakultas_id' => 'ASM',
                'nama' => 'Direktur',
                'nama__en' => 'Director',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '60',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '61',
                'kode_jabatan' => 'PK1',
                'fakultas_id' => 'ASM',
                'nama' => 'Pudir Bidang Akademik',
                'nama__en' => 'Vice Director 1 of Academic Affairs',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'Y',
                'na' => 'N',
                'id_legacy' => '61',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '62',
                'kode_jabatan' => 'PK2',
                'fakultas_id' => 'ASM',
                'nama' => 'Pudir Bidang Adm dan Keuangan ',
                'nama__en' => 'Vice Director 1 of Administration',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => '',
                'na' => 'N',
                'id_legacy' => '62',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '63',
                'kode_jabatan' => 'PK3',
                'fakultas_id' => 'ASM',
                'nama' => 'Pudir Bidang Kemahasiswaan',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '120101110001',
                'tanggal_buat' => null,
                'tgl_buat' => '2012-12-03',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '63',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '64',
                'kode_jabatan' => 'PK4',
                'fakultas_id' => 'ASM',
                'nama' => 'Pudir Bidang Pemasaran',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '64',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '65',
                'kode_jabatan' => 'KK',
                'fakultas_id' => 'ASM',
                'nama' => 'Koordinator Kampus',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '65',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '66',
                'kode_jabatan' => 'KUPT',
                'fakultas_id' => 'ASM',
                'nama' => 'KaBag Unit Penunjang Teknis',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '66',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '67',
                'kode_jabatan' => 'KBAAK',
                'fakultas_id' => 'ASM',
                'nama' => 'KaBag Biro Adm Akademik dan Kemahasiswaan',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '67',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '68',
                'kode_jabatan' => 'KBAU',
                'fakultas_id' => 'ASM',
                'nama' => 'KaBag Biro Adm Umum',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '68',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '69',
                'kode_jabatan' => 'KP2M',
                'fakultas_id' => 'ASM',
                'nama' => 'Kepala P2M',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '69',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '70',
                'kode_jabatan' => 'KJ',
                'fakultas_id' => 'ASM',
                'nama' => 'Ketua Jurusan',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '70',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '71',
                'kode_jabatan' => 'KsPs',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Perpustakaan',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '71',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '72',
                'kode_jabatan' => 'KsT',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Teknis',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '72',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '73',
                'kode_jabatan' => 'KsL',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Laboratorium',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '73',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '74',
                'kode_jabatan' => 'KsP',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Kepegawaian',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '74',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '75',
                'kode_jabatan' => 'Ksk',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Keuangan',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '75',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '76',
                'kode_jabatan' => 'KsKRT',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Kerumahtanggan',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '76',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '77',
                'kode_jabatan' => 'KsTU',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Tata Usaha',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '77',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '78',
                'kode_jabatan' => 'KsRS',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Registrasi dan Statistik',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '78',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '79',
                'kode_jabatan' => 'KsUS',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Ujian dan Sertifikasi',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '79',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '80',
                'kode_jabatan' => 'KsHA',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Humas dan Alumni',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '80',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '81',
                'kode_jabatan' => 'KsPM',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Pembinaan dan Mahasiswa',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '81',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '82',
                'kode_jabatan' => 'KsPP',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Penelitian dan Pengembangan ',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '82',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '83',
                'kode_jabatan' => 'KsPMs',
                'fakultas_id' => 'ASM',
                'nama' => 'KaSi Pengabdian Masyarakat',
                'nama__en' => '',
                'jenis' => '0',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '83',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jabatan_id' => '84',
                'kode_jabatan' => 'KIT',
                'fakultas_id' => 'ASM',
                'nama' => 'KaBag Informasi dan Teknologi',
                'nama__en' => '',
                'jenis' => '1',
                'login_buat' => '',
                'tanggal_buat' => null,
                'tgl_buat' => '0000-00-00',
                'login_edit' => '',
                'tanggal_edit' => null,
                'tgl_edit' => '2016-06-03 08:21:22',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => '84',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Kosongkan tabel sebelum insert
        DB::table('m_jabatan')->truncate();
        
        // Chunk insert untuk performa
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('m_jabatan')->insert($chunk);
        }
    }
}