<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JenisaktivitasSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'jenis_aktivitas_id' => '10',
                'nama' => 'Aktivitas kemahasiswaan',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'N',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '7',
                'nama' => 'Bimbingan akademis',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'N',
                'mbkm' => 'N',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '6',
                'nama' => 'Kerja praktek/PKL',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'N',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '5',
                'nama' => 'Kuliah kerja nyata',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'N',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '4',
                'nama' => 'Disertasi',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'N',
                'mbkm' => 'N',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '3',
                'nama' => 'Tesis',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'N',
                'mbkm' => 'N',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '2',
                'nama' => 'Tugas akhir',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'N',
                'mbkm' => 'N',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '1',
                'nama' => 'Laporan akhir studi',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'N',
                'mbkm' => 'N',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '11',
                'nama' => 'Program kreativitas mahasiswa',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'N',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '12',
                'nama' => 'Kompetisi',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'N',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '13',
                'nama' => 'Magang/Praktik Kerja (Kampus Merdeka)',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'Y',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '14',
                'nama' => 'Asistensi Mengajar di Satuan Pendidikan (Kampus Merdeka)',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'Y',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '15',
                'nama' => 'Penelitian/Riset (Kampus Merdeka)',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'Y',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '16',
                'nama' => 'Proyek Kemanusiaan (Kampus Merdeka)',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'Y',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '17',
                'nama' => 'Kegiatan Wirausaha (Kampus Merdeka)',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'Y',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '18',
                'nama' => 'Studi/Proyek Independen (Kampus Merdeka)',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'Y',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_aktivitas_id' => '19',
                'nama' => 'Membangun Desa/Kuliah Kerja Nyata Tematik (Kampus Merdeka)',
                'kode_id' => 'PI',
                'keterangan' => null,
                'non_akademik' => 'Y',
                'mbkm' => 'Y',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Kosongkan tabel sebelum insert
        DB::table('m_jenisaktivitas')->truncate();
        
        // Chunk insert untuk performa
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('m_jenisaktivitas')->insert($chunk);
        }
    }
}