<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JenispilihanSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'jenis_pilihan_id' => '1',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'Wajib Lulus',
                'prodi_id' => 'BI-D1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '2',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'Wajib Pilihan',
                'prodi_id' => 'BI-D1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '3',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'Wajib Lulus',
                'prodi_id' => 'KA-D1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '4',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'Wajib Lulus',
                'prodi_id' => 'TI-S1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '5',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'WAJIB LULUS',
                'prodi_id' => 'SI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '6',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'Wajib Pilihan',
                'prodi_id' => 'KA-D1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '7',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'Wajib Pilihan',
                'prodi_id' => 'TI-S1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '8',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'WAJIB PILIHAN',
                'prodi_id' => 'SI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '9',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'Wajib Pilihan',
                'prodi_id' => 'MI-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '10',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'WAJIB LULUS',
                'prodi_id' => 'BI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '11',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'WAJIB PILIHAN',
                'prodi_id' => 'BI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '12',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'WAJIB PILIHAN ',
                'prodi_id' => 'MP-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '13',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'WAJIB LULUS',
                'prodi_id' => 'MP-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '14',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'Wajib Lulus',
                'prodi_id' => 'MI-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '15',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'Wajib Lulus',
                'prodi_id' => 'KA-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '16',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'Wajib Pilihan',
                'prodi_id' => 'KA-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '17',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'Wajib Lulus',
                'prodi_id' => 'BJ-D3',
                'ta' => 'N',
                'na' => 'Y',
                'id_legacy' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '18',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'Wajib Pilihan',
                'prodi_id' => 'BJ-D3',
                'ta' => 'N',
                'na' => 'Y',
                'id_legacy' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '22',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'WAJIB LULUS',
                'prodi_id' => 'BI-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '19',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'Wajib Pilihan',
                'prodi_id' => 'MI-D1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '20',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'Wajib Lulus',
                'prodi_id' => 'MI-D1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '23',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'WAJIB PILIHAN',
                'prodi_id' => 'BI-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '24',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'WAJIB LULUS',
                'prodi_id' => 'BJ-D1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '25',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'WAJIB PILIHAN',
                'prodi_id' => 'BJ-D1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '26',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'WAJIB LULUS',
                'prodi_id' => 'SE-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '27',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'WAJIB PILIHAN ',
                'prodi_id' => 'SE-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '28',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'Wajib Lulus',
                'prodi_id' => 'MP-D1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '29',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'Wajib Pilihan',
                'prodi_id' => 'MP-D1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '30',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WL',
                'nama' => 'Wajib Lulus',
                'prodi_id' => 'SE-D1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '31',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'Wajib Pilihan ',
                'prodi_id' => 'SE-D1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '32',
                'kode_id' => 'PI',
                'urutan' => '1',
                'singkatan' => 'A',
                'nama' => 'WAJIB',
                'prodi_id' => 'TI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '32',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '33',
                'kode_id' => 'PI',
                'urutan' => '2',
                'singkatan' => 'B',
                'nama' => 'PILIHAN',
                'prodi_id' => 'TI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '33',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '34',
                'kode_id' => 'PI',
                'urutan' => '3',
                'singkatan' => 'C',
                'nama' => 'WAJIB PEMINATAN',
                'prodi_id' => 'TI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '34',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '35',
                'kode_id' => 'PI',
                'urutan' => '4',
                'singkatan' => 'D',
                'nama' => 'PILIHAN PEMINATAN',
                'prodi_id' => 'TI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '35',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '36',
                'kode_id' => 'PI',
                'urutan' => '5',
                'singkatan' => 'S',
                'nama' => 'TA/SKRIPSI/TESIS/DISERTASI',
                'prodi_id' => 'TI-S1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '37',
                'kode_id' => 'PI',
                'urutan' => '1',
                'singkatan' => 'A',
                'nama' => 'WAJIB',
                'prodi_id' => 'SI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '37',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '38',
                'kode_id' => 'PI',
                'urutan' => '2',
                'singkatan' => 'B',
                'nama' => 'PILIHAN',
                'prodi_id' => 'SI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '39',
                'kode_id' => 'PI',
                'urutan' => '3',
                'singkatan' => 'C',
                'nama' => 'WAJIB PEMINATAN',
                'prodi_id' => 'SI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '39',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '40',
                'kode_id' => 'PI',
                'urutan' => '4',
                'singkatan' => 'D',
                'nama' => 'PILIHAN PEMINATAN',
                'prodi_id' => 'SI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '40',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '41',
                'kode_id' => 'PI',
                'urutan' => '5',
                'singkatan' => 'S',
                'nama' => 'TA/SKRIPSI/TESIS/DISERTASI',
                'prodi_id' => 'SI-S1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '41',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '42',
                'kode_id' => 'PI',
                'urutan' => '1',
                'singkatan' => 'A',
                'nama' => 'WAJIB',
                'prodi_id' => 'KA-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '43',
                'kode_id' => 'PI',
                'urutan' => '2',
                'singkatan' => 'B',
                'nama' => 'PILIHAN',
                'prodi_id' => 'KA-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '44',
                'kode_id' => 'PI',
                'urutan' => '3',
                'singkatan' => 'C',
                'nama' => 'WAJIB PEMINATAN',
                'prodi_id' => 'KA-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '45',
                'kode_id' => 'PI',
                'urutan' => '4',
                'singkatan' => 'D',
                'nama' => 'PILIHAN PEMINATAN',
                'prodi_id' => 'KA-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '46',
                'kode_id' => 'PI',
                'urutan' => '5',
                'singkatan' => 'S',
                'nama' => 'TA/SKRIPSI/TESIS/DISERTASI',
                'prodi_id' => 'KA-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '47',
                'kode_id' => 'PI',
                'urutan' => '1',
                'singkatan' => 'A',
                'nama' => 'WAJIB',
                'prodi_id' => 'MI-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '48',
                'kode_id' => 'PI',
                'urutan' => '2',
                'singkatan' => 'B',
                'nama' => 'PILIHAN',
                'prodi_id' => 'MI-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '48',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '49',
                'kode_id' => 'PI',
                'urutan' => '3',
                'singkatan' => 'C',
                'nama' => 'WAJIB PEMINATAN',
                'prodi_id' => 'MI-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '50',
                'kode_id' => 'PI',
                'urutan' => '4',
                'singkatan' => 'D',
                'nama' => 'PILIHAN PEMINATAN',
                'prodi_id' => 'MI-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '50',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '51',
                'kode_id' => 'PI',
                'urutan' => '5',
                'singkatan' => 'S',
                'nama' => 'TA/SKRIPSI/TESIS/DISERTASI',
                'prodi_id' => 'MI-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '51',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '52',
                'kode_id' => 'PI',
                'urutan' => '1',
                'singkatan' => 'A',
                'nama' => 'WAJIB',
                'prodi_id' => 'BI-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '52',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '53',
                'kode_id' => 'PI',
                'urutan' => '2',
                'singkatan' => 'B',
                'nama' => 'PILIHAN',
                'prodi_id' => 'BI-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '53',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '54',
                'kode_id' => 'PI',
                'urutan' => '3',
                'singkatan' => 'C',
                'nama' => 'WAJIB PEMINATAN',
                'prodi_id' => 'BI-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '54',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '55',
                'kode_id' => 'PI',
                'urutan' => '4',
                'singkatan' => 'D',
                'nama' => 'PILIHAN PEMINATAN',
                'prodi_id' => 'BI-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '55',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '56',
                'kode_id' => 'PI',
                'urutan' => '5',
                'singkatan' => 'S',
                'nama' => 'TA/SKRIPSI/TESIS/DISERTASI',
                'prodi_id' => 'BI-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '56',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '57',
                'kode_id' => 'PI',
                'urutan' => '1',
                'singkatan' => 'A',
                'nama' => 'WAJIB',
                'prodi_id' => 'BI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '57',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '58',
                'kode_id' => 'PI',
                'urutan' => '2',
                'singkatan' => 'B',
                'nama' => 'PILIHAN',
                'prodi_id' => 'BI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '58',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '59',
                'kode_id' => 'PI',
                'urutan' => '3',
                'singkatan' => 'C',
                'nama' => 'WAJIB PEMINATAN',
                'prodi_id' => 'BI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '59',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '60',
                'kode_id' => 'PI',
                'urutan' => '4',
                'singkatan' => 'D',
                'nama' => 'PILIHAN PEMINATAN',
                'prodi_id' => 'BI-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '60',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '61',
                'kode_id' => 'PI',
                'urutan' => '5',
                'singkatan' => 'S',
                'nama' => 'TA/SKRIPSI/TESIS/DISERTASI',
                'prodi_id' => 'BI-S1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '61',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '62',
                'kode_id' => 'PI',
                'urutan' => '1',
                'singkatan' => 'A',
                'nama' => 'WAJIB',
                'prodi_id' => 'BJ-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '62',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '63',
                'kode_id' => 'PI',
                'urutan' => '2',
                'singkatan' => 'B',
                'nama' => 'PILIHAN',
                'prodi_id' => 'BJ-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '63',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '64',
                'kode_id' => 'PI',
                'urutan' => '3',
                'singkatan' => 'C',
                'nama' => 'WAJIB PEMINATAN',
                'prodi_id' => 'BJ-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '64',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '65',
                'kode_id' => 'PI',
                'urutan' => '4',
                'singkatan' => 'D',
                'nama' => 'PILIHAN PEMINATAN',
                'prodi_id' => 'BJ-S1',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '65',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '66',
                'kode_id' => 'PI',
                'urutan' => '5',
                'singkatan' => 'S',
                'nama' => 'TA/SKRIPSI/TESIS/DISERTASI',
                'prodi_id' => 'BJ-S1',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '66',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '67',
                'kode_id' => 'PI',
                'urutan' => '1',
                'singkatan' => 'A',
                'nama' => 'WAJIB',
                'prodi_id' => 'MP-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '67',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '68',
                'kode_id' => 'PI',
                'urutan' => '2',
                'singkatan' => 'B',
                'nama' => 'PILIHAN',
                'prodi_id' => 'MP-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '68',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '69',
                'kode_id' => 'PI',
                'urutan' => '3',
                'singkatan' => 'C',
                'nama' => 'WAJIB PEMINATAN',
                'prodi_id' => 'MP-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '69',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '70',
                'kode_id' => 'PI',
                'urutan' => '4',
                'singkatan' => 'D',
                'nama' => 'PILIHAN PEMINATAN',
                'prodi_id' => 'MP-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '70',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '71',
                'kode_id' => 'PI',
                'urutan' => '5',
                'singkatan' => 'S',
                'nama' => 'TA/SKRIPSI/TESIS/DISERTASI',
                'prodi_id' => 'MP-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '71',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '72',
                'kode_id' => 'PI',
                'urutan' => '1',
                'singkatan' => 'A',
                'nama' => 'WAJIB',
                'prodi_id' => 'SE-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '72',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '73',
                'kode_id' => 'PI',
                'urutan' => '2',
                'singkatan' => 'B',
                'nama' => 'PILIHAN',
                'prodi_id' => 'SE-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '73',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '74',
                'kode_id' => 'PI',
                'urutan' => '3',
                'singkatan' => 'C',
                'nama' => 'WAJIB PEMINATAN',
                'prodi_id' => 'SE-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '74',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '75',
                'kode_id' => 'PI',
                'urutan' => '4',
                'singkatan' => 'D',
                'nama' => 'PILIHAN PEMINATAN',
                'prodi_id' => 'SE-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '75',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '76',
                'kode_id' => 'PI',
                'urutan' => '5',
                'singkatan' => 'S',
                'nama' => 'TA/SKRIPSI/TESIS/DISERTASI',
                'prodi_id' => 'SE-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '76',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '77',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WP',
                'nama' => 'Wajib Program Studi',
                'prodi_id' => 'BJ-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '77',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '78',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'PIL',
                'nama' => 'Pilihan
',
                'prodi_id' => 'BJ-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '78',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '79',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'PEM',
                'nama' => 'Peminatan',
                'prodi_id' => 'BJ-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '79',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '80',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'TA',
                'nama' => 'Tugas Akhir/Skripsi',
                'prodi_id' => 'BJ-D3',
                'ta' => 'Y',
                'na' => 'N',
                'id_legacy' => '80',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenis_pilihan_id' => '81',
                'kode_id' => 'PI',
                'urutan' => '0',
                'singkatan' => 'WN',
                'nama' => 'Wajib Nasional',
                'prodi_id' => 'BJ-D3',
                'ta' => 'N',
                'na' => 'N',
                'id_legacy' => '81',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Kosongkan tabel sebelum insert
        DB::table('m_jenispilihan')->truncate();
        
        // Chunk insert untuk performa
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('m_jenispilihan')->insert($chunk);
        }
    }
}