<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class JenjangSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'jenjang_id' => 'A',
                'dikti_id' => '',
                'jenjang_dikti_id' => '40',
                'nama' => 'S3',
                'keterangan' => 'Strata Tiga',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'B',
                'dikti_id' => '',
                'jenjang_dikti_id' => '35',
                'nama' => 'S2',
                'keterangan' => 'Strata Dua',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'C',
                'dikti_id' => '',
                'jenjang_dikti_id' => '30',
                'nama' => 'S1',
                'keterangan' => 'Strata Satu',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'D',
                'dikti_id' => '',
                'jenjang_dikti_id' => '23',
                'nama' => 'D4',
                'keterangan' => 'Diploma Empat',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'D',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'E',
                'dikti_id' => '',
                'jenjang_dikti_id' => '22',
                'nama' => 'D3',
                'keterangan' => 'Diploma Tiga',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'E',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'F',
                'dikti_id' => '',
                'jenjang_dikti_id' => '21',
                'nama' => 'D2',
                'keterangan' => 'Diploma Dua',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'F',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'G',
                'dikti_id' => '',
                'jenjang_dikti_id' => '20',
                'nama' => 'D1',
                'keterangan' => 'Diploma Satu',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'G',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'H',
                'dikti_id' => '',
                'jenjang_dikti_id' => '32',
                'nama' => 'SP-1',
                'keterangan' => 'Spesialis Satu',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'H',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'I',
                'dikti_id' => '',
                'jenjang_dikti_id' => '37',
                'nama' => 'SP-2',
                'keterangan' => 'Spesialis Dua',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'I',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'J',
                'dikti_id' => '',
                'jenjang_dikti_id' => '31',
                'nama' => 'Profesi',
                'keterangan' => 'Profesi',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'J',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'K',
                'dikti_id' => '',
                'jenjang_dikti_id' => '8',
                'nama' => 'Paket B',
                'keterangan' => null,
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'K',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'L',
                'dikti_id' => '',
                'jenjang_dikti_id' => '9',
                'nama' => 'Paket C',
                'keterangan' => null,
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'M',
                'dikti_id' => '',
                'jenjang_dikti_id' => '0',
                'nama' => 'Tidak Sekolah',
                'keterangan' => null,
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'N',
                'dikti_id' => '',
                'jenjang_dikti_id' => '5',
                'nama' => 'SMP/Sederajat',
                'keterangan' => null,
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'O',
                'dikti_id' => '',
                'jenjang_dikti_id' => '3',
                'nama' => 'Putus SD',
                'keterangan' => null,
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'O',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'P',
                'dikti_id' => '',
                'jenjang_dikti_id' => '1',
                'nama' => 'PAUD',
                'keterangan' => null,
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'Q',
                'dikti_id' => '',
                'jenjang_dikti_id' => '91',
                'nama' => 'Informal',
                'keterangan' => null,
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'Q',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'jenjang_id' => 'R',
                'dikti_id' => '',
                'jenjang_dikti_id' => '',
                'nama' => 'SMA/Sederajat',
                'keterangan' => null,
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'R',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Kosongkan tabel sebelum insert
        DB::table('m_jenjang')->truncate();
        
        // Chunk insert untuk performa
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('m_jenjang')->insert($chunk);
        }
    }
}