<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class KampusSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'kampus_id' => 'PI-C',
                'no_id' => '3',
                'nama' => 'C (Cikarang)',
                'alamat' => 'Jln. Industri Raya No.84 Cikarang',
                'kota' => 'Bekasi',
                'kode_id' => 'PI',
                'telepon' => '021-89109772',
                'wa' => '+6281388222449',
                'fax' => '021-89109772',
                'aktif' => 'N',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'PI-C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kampus_id' => 'PI-A',
                'no_id' => '1',
                'nama' => 'Pusat - Bekasi',
                'alamat' => 'Jln. Cut Meutia No.28, Margahayu, Bekasi Timur',
                'kota' => 'Kota Bekasi',
                'kode_id' => 'PI',
                'telepon' => '021-8806757',
                'wa' => '+6281388222449',
                'fax' => '021-8806757',
                'aktif' => 'Y',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'PI-A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kampus_id' => 'PI-B',
                'no_id' => '2',
                'nama' => 'Pondok Gede',
                'alamat' => 'Jln. Raya Pondok Gede No 21, Pondok Melati, Pondok Gede',
                'kota' => 'Kota Bekasi',
                'kode_id' => 'PI',
                'telepon' => '+6221-8467364',
                'wa' => '+6281388222449',
                'fax' => '021-8467364',
                'aktif' => 'Y',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'PI-B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kampus_id' => 'PI-D',
                'no_id' => '4',
                'nama' => 'D (Bogor)',
                'alamat' => 'Jln. Merdeka No. 46',
                'kota' => 'Bogor',
                'kode_id' => 'PI',
                'telepon' => '0251-322448',
                'wa' => '+6281388222449',
                'fax' => '0251-322448',
                'aktif' => 'N',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'PI-D',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kampus_id' => 'PI-E',
                'no_id' => '5',
                'nama' => 'E (Parung Panjang)',
                'alamat' => 'Jln. Sayuti No 28 Parung',
                'kota' => 'Tangerang',
                'kode_id' => 'PI',
                'telepon' => '0251-68081563',
                'wa' => '+6281388222449',
                'fax' => '0251-68081563',
                'aktif' => 'N',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'PI-E',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kampus_id' => 'PI-F',
                'no_id' => '6',
                'nama' => 'F (Karawang)',
                'alamat' => 'Jln. Suroto Kunto No.47 Karawang',
                'kota' => 'Karawang',
                'kode_id' => 'PI',
                'telepon' => '0267-400475',
                'wa' => '+6281388222449',
                'fax' => '0267-400475',
                'aktif' => 'N',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'PI-F',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kampus_id' => 'PI-G',
                'no_id' => '7',
                'nama' => 'STBA Bekasi',
                'alamat' => 'Jln. Cut Meutia No.28, Margahayu, Bekasi Timur',
                'kota' => 'Kota Bekasi',
                'kode_id' => 'PI',
                'telepon' => '021-8802297',
                'wa' => '+6285714647616',
                'fax' => '021-8800557',
                'aktif' => 'Y',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'PI-G',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kampus_id' => 'PI-H',
                'no_id' => '8',
                'nama' => 'Cileungsi',
                'alamat' => 'Jln. Raya Narogong Blok D No 10-11 (Cileungsi Trade Center/Mall Cileungsi)',
                'kota' => 'Bogor',
                'kode_id' => 'PI',
                'telepon' => '02182482930',
                'wa' => '+6281388222449',
                'fax' => '02136061032',
                'aktif' => 'N',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'PI-H',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kampus_id' => 'PI-J',
                'no_id' => '12',
                'nama' => 'J',
                'alamat' => '-',
                'kota' => 'Bekasi',
                'kode_id' => 'PI',
                'telepon' => '',
                'wa' => '+6281388222449',
                'fax' => '',
                'aktif' => 'N',
                'def' => 'N',
                'na' => 'N',
                'id_legacy' => 'PI-J',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'kampus_id' => 'PI-K',
                'no_id' => '13',
                'nama' => 'Pengasinan',
                'alamat' => 'Jln. Pengasinan Tengah, No 100, Bekasi Timur',
                'kota' => 'Kota Bekasi',
                'kode_id' => 'PI',
                'telepon' => '',
                'wa' => '+6281388222449',
                'fax' => '',
                'aktif' => 'Y',
                'def' => 'Y',
                'na' => 'N',
                'id_legacy' => 'PI-K',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Kosongkan tabel sebelum insert
        DB::table('m_kampus')->truncate();
        
        // Chunk insert untuk performa
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('m_kampus')->insert($chunk);
        }
    }
}