<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class NegaraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'negara_id' => '2',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '01',
                'kode_huruf' => 'ID',
                'nama' => 'INDONESIA',
                'na' => 'N',
                'id_legacy' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '3',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '02',
                'kode_huruf' => '',
                'nama' => 'JAPAN',
                'na' => 'N',
                'id_legacy' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '4',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '03',
                'kode_huruf' => '',
                'nama' => 'SOUTH KOREA',
                'na' => 'N',
                'id_legacy' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '5',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '05',
                'kode_huruf' => '',
                'nama' => 'TAIWAN',
                'na' => 'N',
                'id_legacy' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '6',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '06',
                'kode_huruf' => '',
                'nama' => 'PHILIPPINES',
                'na' => 'N',
                'id_legacy' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '7',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '07',
                'kode_huruf' => '',
                'nama' => 'MALAYSIA',
                'na' => 'N',
                'id_legacy' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '8',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '08',
                'kode_huruf' => '',
                'nama' => 'BRUNEI DARUSSALAM',
                'na' => 'N',
                'id_legacy' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '9',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '09',
                'kode_huruf' => '',
                'nama' => 'SINGAPORE',
                'na' => 'N',
                'id_legacy' => '9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '10',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '10',
                'kode_huruf' => '',
                'nama' => 'THAILAND',
                'na' => 'N',
                'id_legacy' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '11',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '12',
                'kode_huruf' => '',
                'nama' => 'INDIA',
                'na' => 'N',
                'id_legacy' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '12',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '13',
                'kode_huruf' => '',
                'nama' => 'PAKISTAN',
                'na' => 'N',
                'id_legacy' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '13',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '14',
                'kode_huruf' => '',
                'nama' => 'SRI LANGKA',
                'na' => 'N',
                'id_legacy' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '14',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '15',
                'kode_huruf' => '',
                'nama' => 'VIETNAM',
                'na' => 'N',
                'id_legacy' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '15',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '16',
                'kode_huruf' => '',
                'nama' => 'MYANMAR',
                'na' => 'N',
                'id_legacy' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '16',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '17',
                'kode_huruf' => '',
                'nama' => 'LAOS',
                'na' => 'N',
                'id_legacy' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '17',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '11',
                'kode_huruf' => '',
                'nama' => 'CHINA',
                'na' => 'N',
                'id_legacy' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '18',
                'kode_benua' => '95',
                'nama_benua' => 'AMERIKA',
                'kode_negara' => '01',
                'kode_huruf' => '',
                'nama' => 'CANADA',
                'na' => 'N',
                'id_legacy' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '19',
                'kode_benua' => '95',
                'nama_benua' => 'AMERIKA',
                'kode_negara' => '02',
                'kode_huruf' => '',
                'nama' => 'UNITED STATES OF AMERICA',
                'na' => 'N',
                'id_legacy' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '20',
                'kode_benua' => '95',
                'nama_benua' => 'AMERIKA',
                'kode_negara' => '03',
                'kode_huruf' => '',
                'nama' => 'MEXICO',
                'na' => 'N',
                'id_legacy' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '21',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '01',
                'kode_huruf' => '',
                'nama' => 'UNITED KINGDOM',
                'na' => 'N',
                'id_legacy' => '21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '22',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '02',
                'kode_huruf' => '',
                'nama' => 'FRANCE',
                'na' => 'N',
                'id_legacy' => '22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '23',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '03',
                'kode_huruf' => '',
                'nama' => 'BELGIUM',
                'na' => 'N',
                'id_legacy' => '23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '24',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '04',
                'kode_huruf' => '',
                'nama' => 'NETHERLANDS',
                'na' => 'N',
                'id_legacy' => '24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '25',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '05',
                'kode_huruf' => '',
                'nama' => 'GERMANY',
                'na' => 'N',
                'id_legacy' => '25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '26',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '06',
                'kode_huruf' => '',
                'nama' => 'ITALY',
                'na' => 'N',
                'id_legacy' => '26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '27',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '07',
                'kode_huruf' => '',
                'nama' => 'AUSTRIA',
                'na' => 'N',
                'id_legacy' => '27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '28',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '08',
                'kode_huruf' => '',
                'nama' => 'POLAND',
                'na' => 'N',
                'id_legacy' => '28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '29',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '09',
                'kode_huruf' => '',
                'nama' => 'CZECH REPUBLIC',
                'na' => 'N',
                'id_legacy' => '29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '30',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '10',
                'kode_huruf' => '',
                'nama' => 'HUNGARY',
                'na' => 'N',
                'id_legacy' => '30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '31',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '11',
                'kode_huruf' => '',
                'nama' => 'BULGARIA',
                'na' => 'N',
                'id_legacy' => '31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '32',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '12',
                'kode_huruf' => '',
                'nama' => 'ROMANIA',
                'na' => 'N',
                'id_legacy' => '32',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '33',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '13',
                'kode_huruf' => '',
                'nama' => 'SWEDEN',
                'na' => 'N',
                'id_legacy' => '33',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '34',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '14',
                'kode_huruf' => '',
                'nama' => 'NORWAY',
                'na' => 'N',
                'id_legacy' => '34',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '35',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '15',
                'kode_huruf' => '',
                'nama' => 'FINLAND',
                'na' => 'N',
                'id_legacy' => '35',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '36',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '16',
                'kode_huruf' => '',
                'nama' => 'RUSSIA',
                'na' => 'N',
                'id_legacy' => '36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '37',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '17',
                'kode_huruf' => '',
                'nama' => 'PORTUGAL',
                'na' => 'N',
                'id_legacy' => '37',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '38',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '18',
                'kode_huruf' => '',
                'nama' => 'SPAIN',
                'na' => 'N',
                'id_legacy' => '38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '39',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '01',
                'kode_huruf' => '',
                'nama' => 'AUSTRALIA',
                'na' => 'N',
                'id_legacy' => '39',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '40',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '02',
                'kode_huruf' => '',
                'nama' => 'NEW ZEALAND',
                'na' => 'N',
                'id_legacy' => '40',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '41',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '18',
                'kode_huruf' => '',
                'nama' => 'SAUDI ARABIA',
                'na' => 'N',
                'id_legacy' => '41',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '42',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '19',
                'kode_huruf' => '',
                'nama' => 'TURKEY',
                'na' => 'N',
                'id_legacy' => '42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '43',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '20',
                'kode_huruf' => 'AF',
                'nama' => 'AFGHANISTAN',
                'na' => 'N',
                'id_legacy' => '43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '44',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '21',
                'kode_huruf' => '',
                'nama' => 'IRAN',
                'na' => 'N',
                'id_legacy' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '45',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '22',
                'kode_huruf' => '',
                'nama' => 'IRAQ',
                'na' => 'N',
                'id_legacy' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '46',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '23',
                'kode_huruf' => '',
                'nama' => 'SYRIA',
                'na' => 'N',
                'id_legacy' => '46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '47',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '04',
                'kode_huruf' => '',
                'nama' => 'NORTH KOREA',
                'na' => 'N',
                'id_legacy' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '48',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '24',
                'kode_huruf' => '',
                'nama' => 'BAHRAIN',
                'na' => 'N',
                'id_legacy' => '48',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '49',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '25',
                'kode_huruf' => '',
                'nama' => 'QATAR',
                'na' => 'N',
                'id_legacy' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '50',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '26',
                'kode_huruf' => '',
                'nama' => 'KUWAIT',
                'na' => 'N',
                'id_legacy' => '50',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '51',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '27',
                'kode_huruf' => '',
                'nama' => 'UNITED ARAB EMIRATES',
                'na' => 'N',
                'id_legacy' => '51',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '52',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '01',
                'kode_huruf' => '',
                'nama' => 'EGYPT',
                'na' => 'N',
                'id_legacy' => '52',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '53',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '28',
                'kode_huruf' => '',
                'nama' => 'BANGLADESH',
                'na' => 'N',
                'id_legacy' => '53',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '54',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '29',
                'kode_huruf' => '',
                'nama' => 'JORDAN',
                'na' => 'N',
                'id_legacy' => '54',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '55',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '19',
                'kode_huruf' => '',
                'nama' => 'MONACO',
                'na' => 'N',
                'id_legacy' => '55',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '56',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '20',
                'kode_huruf' => '',
                'nama' => 'SWITZERLANDS',
                'na' => 'N',
                'id_legacy' => '56',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '57',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '21',
                'kode_huruf' => '',
                'nama' => 'DENMARK',
                'na' => 'N',
                'id_legacy' => '57',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '58',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '22',
                'kode_huruf' => '',
                'nama' => 'SLOVAKIA',
                'na' => 'N',
                'id_legacy' => '58',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '59',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '02',
                'kode_huruf' => '',
                'nama' => 'TUNISIA',
                'na' => 'N',
                'id_legacy' => '59',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '60',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '03',
                'kode_huruf' => '',
                'nama' => 'MOROCCO',
                'na' => 'N',
                'id_legacy' => '60',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '61',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '04',
                'kode_huruf' => '',
                'nama' => 'ALGERIA',
                'na' => 'N',
                'id_legacy' => '61',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '62',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '05',
                'kode_huruf' => '',
                'nama' => 'GHANA',
                'na' => 'N',
                'id_legacy' => '62',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '63',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '06',
                'kode_huruf' => '',
                'nama' => 'NIGERIA',
                'na' => 'N',
                'id_legacy' => '63',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '64',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '07',
                'kode_huruf' => '',
                'nama' => 'SOUTH AFRICA',
                'na' => 'N',
                'id_legacy' => '64',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '65',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '08',
                'kode_huruf' => '',
                'nama' => 'SUDAN',
                'na' => 'N',
                'id_legacy' => '65',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '66',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '09',
                'kode_huruf' => '',
                'nama' => 'LIBYA',
                'na' => 'N',
                'id_legacy' => '66',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '67',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '23',
                'kode_huruf' => '',
                'nama' => 'IRELAND',
                'na' => 'N',
                'id_legacy' => '67',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '68',
                'kode_benua' => '95',
                'nama_benua' => 'AMERIKA',
                'kode_negara' => '04',
                'kode_huruf' => '',
                'nama' => 'BRAZIL',
                'na' => 'N',
                'id_legacy' => '68',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '69',
                'kode_benua' => '95',
                'nama_benua' => 'AMERIKA',
                'kode_negara' => '05',
                'kode_huruf' => '',
                'nama' => 'ARGENTINA',
                'na' => 'N',
                'id_legacy' => '69',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '70',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '30',
                'kode_huruf' => '',
                'nama' => 'YEMEN',
                'na' => 'N',
                'id_legacy' => '70',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '71',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '31',
                'kode_huruf' => '',
                'nama' => 'ISRAEL',
                'na' => 'N',
                'id_legacy' => '71',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '72',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '32',
                'kode_huruf' => '',
                'nama' => 'OMAN',
                'na' => 'N',
                'id_legacy' => '72',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '73',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '10',
                'kode_huruf' => '',
                'nama' => 'MAURITANIA',
                'na' => 'N',
                'id_legacy' => '73',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '74',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '11',
                'kode_huruf' => '',
                'nama' => 'MALI',
                'na' => 'N',
                'id_legacy' => '74',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '75',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '12',
                'kode_huruf' => '',
                'nama' => 'SENEGAL',
                'na' => 'N',
                'id_legacy' => '75',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '76',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '13',
                'kode_huruf' => '',
                'nama' => 'CONGO',
                'na' => 'N',
                'id_legacy' => '76',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '77',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '14',
                'kode_huruf' => '',
                'nama' => 'GABON',
                'na' => 'N',
                'id_legacy' => '77',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '78',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '15',
                'kode_huruf' => '',
                'nama' => 'ZAIRE',
                'na' => 'N',
                'id_legacy' => '78',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '79',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '16',
                'kode_huruf' => '',
                'nama' => 'TANZANIA',
                'na' => 'N',
                'id_legacy' => '79',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '80',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '17',
                'kode_huruf' => '',
                'nama' => 'KENYA',
                'na' => 'N',
                'id_legacy' => '80',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '81',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '18',
                'kode_huruf' => '',
                'nama' => 'SOMALIA',
                'na' => 'N',
                'id_legacy' => '81',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '82',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '19',
                'kode_huruf' => '',
                'nama' => 'MALAGASY',
                'na' => 'N',
                'id_legacy' => '82',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '83',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '20',
                'kode_huruf' => '',
                'nama' => 'MOZAMBIQUE',
                'na' => 'N',
                'id_legacy' => '83',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '84',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '21',
                'kode_huruf' => '',
                'nama' => 'NAMIBIA',
                'na' => 'N',
                'id_legacy' => '84',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '85',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '22',
                'kode_huruf' => '',
                'nama' => 'BOSTWANA',
                'na' => 'N',
                'id_legacy' => '85',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '86',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '23',
                'kode_huruf' => '',
                'nama' => 'ZIMBABWE',
                'na' => 'N',
                'id_legacy' => '86',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '87',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '24',
                'kode_huruf' => '',
                'nama' => 'ZAMBIA',
                'na' => 'N',
                'id_legacy' => '87',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '88',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '25',
                'kode_huruf' => '',
                'nama' => 'MALAWI',
                'na' => 'N',
                'id_legacy' => '88',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '89',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '26',
                'kode_huruf' => '',
                'nama' => 'ANGOLA',
                'na' => 'N',
                'id_legacy' => '89',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '90',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '27',
                'kode_huruf' => '',
                'nama' => 'UGANDA',
                'na' => 'N',
                'id_legacy' => '90',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '91',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '28',
                'kode_huruf' => '',
                'nama' => 'LIBERIA',
                'na' => 'N',
                'id_legacy' => '91',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '92',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '29',
                'kode_huruf' => '',
                'nama' => 'SIERRA LEONE',
                'na' => 'N',
                'id_legacy' => '92',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '93',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '30',
                'kode_huruf' => '',
                'nama' => 'GAMBIA',
                'na' => 'N',
                'id_legacy' => '93',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '94',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '31',
                'kode_huruf' => '',
                'nama' => 'GUINEA',
                'na' => 'N',
                'id_legacy' => '94',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '95',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '32',
                'kode_huruf' => '',
                'nama' => 'IVORY COAST',
                'na' => 'N',
                'id_legacy' => '95',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '96',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '33',
                'kode_huruf' => '',
                'nama' => 'CHAD',
                'na' => 'N',
                'id_legacy' => '96',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '97',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '34',
                'kode_huruf' => '',
                'nama' => 'NIGER',
                'na' => 'N',
                'id_legacy' => '97',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '98',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '35',
                'kode_huruf' => '',
                'nama' => 'BURKINA',
                'na' => 'N',
                'id_legacy' => '98',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '99',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '36',
                'kode_huruf' => '',
                'nama' => 'BENIN',
                'na' => 'N',
                'id_legacy' => '99',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '100',
                'kode_benua' => '98',
                'nama_benua' => 'AFRICA',
                'kode_negara' => '37',
                'kode_huruf' => '',
                'nama' => 'CENTRAL AFRICAN REPUBLIC',
                'na' => 'N',
                'id_legacy' => '100',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '101',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '34',
                'kode_huruf' => '',
                'nama' => 'MONGOLIA',
                'na' => 'N',
                'id_legacy' => '101',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '102',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '35',
                'kode_huruf' => '',
                'nama' => 'CHINA, MACAU',
                'na' => 'N',
                'id_legacy' => '102',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '103',
                'kode_benua' => '95',
                'nama_benua' => 'AMERIKA',
                'kode_negara' => '06',
                'kode_huruf' => '',
                'nama' => 'PERU',
                'na' => 'N',
                'id_legacy' => '103',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '104',
                'kode_benua' => '95',
                'nama_benua' => 'AMERIKA',
                'kode_negara' => '07',
                'kode_huruf' => '',
                'nama' => 'COLOMBIA',
                'na' => 'N',
                'id_legacy' => '104',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '105',
                'kode_benua' => '95',
                'nama_benua' => 'AMERIKA',
                'kode_negara' => '08',
                'kode_huruf' => '',
                'nama' => 'PANAMA',
                'na' => 'N',
                'id_legacy' => '105',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '106',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '24',
                'kode_huruf' => '',
                'nama' => 'BELARUS',
                'na' => 'N',
                'id_legacy' => '106',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '107',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '25',
                'kode_huruf' => '',
                'nama' => 'LUXEMBOURG',
                'na' => 'N',
                'id_legacy' => '107',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '108',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '26',
                'kode_huruf' => '',
                'nama' => 'UKRAINE',
                'na' => 'N',
                'id_legacy' => '108',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '109',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '27',
                'kode_huruf' => '',
                'nama' => 'ESTONIA',
                'na' => 'N',
                'id_legacy' => '109',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '110',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '28',
                'kode_huruf' => '',
                'nama' => 'ALBANIA',
                'na' => 'N',
                'id_legacy' => '110',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '111',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '29',
                'kode_huruf' => '',
                'nama' => 'GUERNSEY',
                'na' => 'N',
                'id_legacy' => '111',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '112',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '30',
                'kode_huruf' => '',
                'nama' => 'ICELAND',
                'na' => 'N',
                'id_legacy' => '112',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '113',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '31',
                'kode_huruf' => '',
                'nama' => 'JERSEY',
                'na' => 'N',
                'id_legacy' => '113',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '114',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '32',
                'kode_huruf' => '',
                'nama' => 'LATVIA',
                'na' => 'N',
                'id_legacy' => '114',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '115',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '33',
                'kode_huruf' => '',
                'nama' => 'LITHUANIA',
                'na' => 'N',
                'id_legacy' => '115',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '116',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '34',
                'kode_huruf' => '',
                'nama' => 'ISLE OF MAN',
                'na' => 'N',
                'id_legacy' => '116',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '117',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '35',
                'kode_huruf' => '',
                'nama' => 'SVALBARD',
                'na' => 'N',
                'id_legacy' => '117',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '118',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '36',
                'kode_huruf' => '',
                'nama' => 'GREECE',
                'na' => 'N',
                'id_legacy' => '118',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '119',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '37',
                'kode_huruf' => '',
                'nama' => 'ANDORRA',
                'na' => 'N',
                'id_legacy' => '119',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '120',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '38',
                'kode_huruf' => '',
                'nama' => 'BOSNIA AND HERZEGOVINA',
                'na' => 'N',
                'id_legacy' => '120',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '121',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '39',
                'kode_huruf' => '',
                'nama' => 'CROATIA',
                'na' => 'N',
                'id_legacy' => '121',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '122',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '40',
                'kode_huruf' => '',
                'nama' => 'GIBRALTAR',
                'na' => 'N',
                'id_legacy' => '122',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '123',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '41',
                'kode_huruf' => '',
                'nama' => 'SLOVENIA',
                'na' => 'N',
                'id_legacy' => '123',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '124',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '42',
                'kode_huruf' => '',
                'nama' => 'HOLY SEE (VATICAN CITY)',
                'na' => 'N',
                'id_legacy' => '124',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '125',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '43',
                'kode_huruf' => '',
                'nama' => 'MACEDONIA',
                'na' => 'N',
                'id_legacy' => '125',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '126',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '44',
                'kode_huruf' => '',
                'nama' => 'MALTA',
                'na' => 'N',
                'id_legacy' => '126',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '127',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '45',
                'kode_huruf' => '',
                'nama' => 'SAN MARINO',
                'na' => 'N',
                'id_legacy' => '127',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '128',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '46',
                'kode_huruf' => '',
                'nama' => 'SERBIA AND MONTENEGRO',
                'na' => 'N',
                'id_legacy' => '128',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '129',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '47',
                'kode_huruf' => '',
                'nama' => 'MOLDOVA',
                'na' => 'N',
                'id_legacy' => '129',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '130',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '48',
                'kode_huruf' => '',
                'nama' => 'LIECHTENSTEIN',
                'na' => 'N',
                'id_legacy' => '130',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '131',
                'kode_benua' => '96',
                'nama_benua' => 'EUROPE',
                'kode_negara' => '49',
                'kode_huruf' => '',
                'nama' => 'FAROE ISLAND',
                'na' => 'N',
                'id_legacy' => '131',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '132',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '09',
                'kode_huruf' => '',
                'nama' => 'CHILE',
                'na' => 'N',
                'id_legacy' => '132',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '133',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '10',
                'kode_huruf' => '',
                'nama' => 'PARAGUAY',
                'na' => 'N',
                'id_legacy' => '133',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '134',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '11',
                'kode_huruf' => '',
                'nama' => 'URUGUAY',
                'na' => 'N',
                'id_legacy' => '134',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '135',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '12',
                'kode_huruf' => '',
                'nama' => 'VENEZUELA',
                'na' => 'N',
                'id_legacy' => '135',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '136',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '13',
                'kode_huruf' => '',
                'nama' => 'BOLIVIA',
                'na' => 'N',
                'id_legacy' => '136',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '137',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '14',
                'kode_huruf' => '',
                'nama' => 'ECUADOR',
                'na' => 'N',
                'id_legacy' => '137',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '138',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '15',
                'kode_huruf' => '',
                'nama' => 'FALKLAND ISLANDS',
                'na' => 'N',
                'id_legacy' => '138',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '139',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '16',
                'kode_huruf' => '',
                'nama' => 'FRENCH GUIANA',
                'na' => 'N',
                'id_legacy' => '139',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '140',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '17',
                'kode_huruf' => '',
                'nama' => 'GUYANA',
                'na' => 'N',
                'id_legacy' => '140',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '141',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '18',
                'kode_huruf' => '',
                'nama' => 'SURINAME',
                'na' => 'N',
                'id_legacy' => '141',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '142',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '19',
                'kode_huruf' => '',
                'nama' => 'COSTA RICA',
                'na' => 'N',
                'id_legacy' => '142',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '143',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '20',
                'kode_huruf' => '',
                'nama' => 'EL SALVADOR',
                'na' => 'N',
                'id_legacy' => '143',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '144',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '21',
                'kode_huruf' => '',
                'nama' => 'GUATEMALA',
                'na' => 'N',
                'id_legacy' => '144',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '145',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '22',
                'kode_huruf' => '',
                'nama' => 'HONDURAS',
                'na' => 'N',
                'id_legacy' => '145',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '146',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '23',
                'kode_huruf' => '',
                'nama' => 'NICARAGUA',
                'na' => 'N',
                'id_legacy' => '146',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '147',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '24',
                'kode_huruf' => '',
                'nama' => 'BELIZE',
                'na' => 'N',
                'id_legacy' => '147',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '148',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '25',
                'kode_huruf' => '',
                'nama' => 'BERMUDA',
                'na' => 'N',
                'id_legacy' => '148',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '149',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '26',
                'kode_huruf' => '',
                'nama' => 'GREENLAND',
                'na' => 'N',
                'id_legacy' => '149',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '150',
                'kode_benua' => '95',
                'nama_benua' => 'AMERICA',
                'kode_negara' => '27',
                'kode_huruf' => '',
                'nama' => 'SAINT PIERRE AND MIQUELON',
                'na' => 'N',
                'id_legacy' => '150',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '151',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '03',
                'kode_huruf' => '',
                'nama' => 'NORFOLK ISLAND',
                'na' => 'N',
                'id_legacy' => '151',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '152',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '04',
                'kode_huruf' => '',
                'nama' => 'FIJI',
                'na' => 'N',
                'id_legacy' => '152',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '153',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '05',
                'kode_huruf' => '',
                'nama' => 'NEW CALEDONIA',
                'na' => 'N',
                'id_legacy' => '153',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '154',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '06',
                'kode_huruf' => '',
                'nama' => 'PAPUA NEW GUINEA',
                'na' => 'N',
                'id_legacy' => '154',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '155',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '07',
                'kode_huruf' => '',
                'nama' => 'SOLOMON ISLANDS',
                'na' => 'N',
                'id_legacy' => '155',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '156',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '08',
                'kode_huruf' => '',
                'nama' => 'VANUATU',
                'na' => 'N',
                'id_legacy' => '156',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '157',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '09',
                'kode_huruf' => '',
                'nama' => 'GUAM',
                'na' => 'N',
                'id_legacy' => '157',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '158',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '10',
                'kode_huruf' => '',
                'nama' => 'KIRIBATI',
                'na' => 'N',
                'id_legacy' => '158',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '159',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '11',
                'kode_huruf' => '',
                'nama' => 'MARSHALL ISLANDS',
                'na' => 'N',
                'id_legacy' => '159',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '160',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '12',
                'kode_huruf' => '',
                'nama' => 'FEDERATED STATES OF MICRONESIA',
                'na' => 'N',
                'id_legacy' => '160',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '161',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '13',
                'kode_huruf' => '',
                'nama' => 'NAURU',
                'na' => 'N',
                'id_legacy' => '161',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '162',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '14',
                'kode_huruf' => '',
                'nama' => 'NORTHERN MARIANA ISLANDS',
                'na' => 'N',
                'id_legacy' => '162',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '163',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '15',
                'kode_huruf' => '',
                'nama' => 'PALAU',
                'na' => 'N',
                'id_legacy' => '163',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '164',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '16',
                'kode_huruf' => '',
                'nama' => 'AMERICAN SAMOA',
                'na' => 'N',
                'id_legacy' => '164',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '165',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '17',
                'kode_huruf' => '',
                'nama' => 'COOK ISLANDS',
                'na' => 'N',
                'id_legacy' => '165',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '166',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '18',
                'kode_huruf' => '',
                'nama' => 'FRENCH POLYNESIA',
                'na' => 'N',
                'id_legacy' => '166',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '167',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '19',
                'kode_huruf' => '',
                'nama' => 'NIUE',
                'na' => 'N',
                'id_legacy' => '167',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '168',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '20',
                'kode_huruf' => '',
                'nama' => 'PITCAIRN ISLANDS',
                'na' => 'N',
                'id_legacy' => '168',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '169',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '21',
                'kode_huruf' => '',
                'nama' => 'SAMOA',
                'na' => 'N',
                'id_legacy' => '169',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '170',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '22',
                'kode_huruf' => '',
                'nama' => 'TOKELAU',
                'na' => 'N',
                'id_legacy' => '170',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '171',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '23',
                'kode_huruf' => '',
                'nama' => 'TONGA',
                'na' => 'N',
                'id_legacy' => '171',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '172',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '24',
                'kode_huruf' => '',
                'nama' => 'TUVALU',
                'na' => 'N',
                'id_legacy' => '172',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '173',
                'kode_benua' => '97',
                'nama_benua' => 'AUSTRALIA',
                'kode_negara' => '25',
                'kode_huruf' => '',
                'nama' => 'WALLIS AND FUTUNA',
                'na' => 'N',
                'id_legacy' => '173',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '174',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '36',
                'kode_huruf' => '',
                'nama' => 'CHINA, HONG KONG SAR',
                'na' => 'N',
                'id_legacy' => '174',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '175',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '37',
                'kode_huruf' => '',
                'nama' => 'BHUTAN',
                'na' => 'N',
                'id_legacy' => '175',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '176',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '38',
                'kode_huruf' => '',
                'nama' => 'KAZAKHSTAN',
                'na' => 'N',
                'id_legacy' => '176',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '177',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '39',
                'kode_huruf' => '',
                'nama' => 'KYRGYZSTAN',
                'na' => 'N',
                'id_legacy' => '177',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '178',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '40',
                'kode_huruf' => '',
                'nama' => 'MALDIVES',
                'na' => 'N',
                'id_legacy' => '178',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '179',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '41',
                'kode_huruf' => '',
                'nama' => 'NEPAL',
                'na' => 'N',
                'id_legacy' => '179',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '180',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '42',
                'kode_huruf' => '',
                'nama' => 'TAJIKISTAN',
                'na' => 'N',
                'id_legacy' => '180',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '181',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '43',
                'kode_huruf' => '',
                'nama' => 'TURKMENISTAN',
                'na' => 'N',
                'id_legacy' => '181',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '182',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '44',
                'kode_huruf' => '',
                'nama' => 'UZBEKISTAN',
                'na' => 'N',
                'id_legacy' => '182',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '183',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '45',
                'kode_huruf' => '',
                'nama' => 'CAMBODIA',
                'na' => 'N',
                'id_legacy' => '183',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '184',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '46',
                'kode_huruf' => '',
                'nama' => 'ARMENIA',
                'na' => 'N',
                'id_legacy' => '184',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '185',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '47',
                'kode_huruf' => '',
                'nama' => 'AZERBAIJAN',
                'na' => 'N',
                'id_legacy' => '185',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '186',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '48',
                'kode_huruf' => '',
                'nama' => 'CYPRUS',
                'na' => 'N',
                'id_legacy' => '186',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '187',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '49',
                'kode_huruf' => '',
                'nama' => 'GEORGIA',
                'na' => 'N',
                'id_legacy' => '187',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '188',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '50',
                'kode_huruf' => '',
                'nama' => 'PALESTINIAN TERRITORY',
                'na' => 'N',
                'id_legacy' => '188',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'negara_id' => '189',
                'kode_benua' => '94',
                'nama_benua' => 'ASIA',
                'kode_negara' => '33',
                'kode_huruf' => '',
                'nama' => 'TIMOR LESTE',
                'na' => 'N',
                'id_legacy' => '189',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Kosongkan tabel sebelum insert
        DB::table('m_negara')->truncate();
        
        // Chunk insert untuk performa
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('m_negara')->insert($chunk);
        }
    }
}