<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class StatusmhswSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'status_mhsw_id' => 'A',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Aktif',
                'nilai' => '1',
                'status_semester' => 'Y',
                'keluar' => 'N',
                'status_kembali' => 'N',
                'def' => 'Y',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'C',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Cuti',
                'nilai' => '0',
                'status_semester' => 'Y',
                'keluar' => 'N',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'C',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'N',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Non Aktif',
                'nilai' => '1',
                'status_semester' => 'Y',
                'keluar' => 'N',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'K',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Keluar',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'Y',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'Y',
                'id_legacy' => 'K',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'D',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Drop-Out/Putus Studi',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'Y',
                'id_legacy' => 'D',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'L',
                'jenis_keluar_id' => '1',
                'kode_id' => 'PI',
                'nama' => 'Lulus',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'Y',
                'na' => 'N',
                'id_legacy' => 'L',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'T',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Tunggu Ujian',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'N',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'Y',
                'id_legacy' => 'T',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'W',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Tunggu Wisuda',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'N',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'Y',
                'na' => 'Y',
                'id_legacy' => 'W',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'S',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Skorsing',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'N',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'Y',
                'id_legacy' => 'S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'G',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Sedang Double Degree',
                'nilai' => '0',
                'status_semester' => 'Y',
                'keluar' => 'N',
                'status_kembali' => 'Y',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'Y',
                'id_legacy' => 'G',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'MD',
                'jenis_keluar_id' => '4',
                'kode_id' => 'PI',
                'nama' => 'Mengundurkan Diri',
                'nilai' => '1',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'Y',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'MD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'DK',
                'jenis_keluar_id' => '3',
                'kode_id' => 'PI',
                'nama' => 'Dikeluarkan',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'DK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'X',
                'jenis_keluar_id' => '10',
                'kode_id' => 'PI',
                'nama' => 'Lainnya',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'X',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'M',
                'jenis_keluar_id' => '2',
                'kode_id' => 'PI',
                'nama' => 'Mutasi',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'Y',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'H',
                'jenis_keluar_id' => '7',
                'kode_id' => 'PI',
                'nama' => 'Hilang',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'H',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'P',
                'jenis_keluar_id' => '9',
                'kode_id' => 'PI',
                'nama' => 'Pensiun',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'Y',
                'id_legacy' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'PS',
                'jenis_keluar_id' => '5',
                'kode_id' => 'PI',
                'nama' => 'Putus Sekolah',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'Y',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'PS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'WF',
                'jenis_keluar_id' => '6',
                'kode_id' => 'PI',
                'nama' => 'Wafat',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'WF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'KM',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Kampus Merdeka',
                'nilai' => '0',
                'status_semester' => 'Y',
                'keluar' => 'N',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'KM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'KOM',
                'jenis_keluar_id' => '0',
                'kode_id' => 'PI',
                'nama' => 'Menunggu Ujikom',
                'nilai' => '0',
                'status_semester' => 'Y',
                'keluar' => 'N',
                'status_kembali' => 'N',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'KOM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'status_mhsw_id' => 'PSt',
                'jenis_keluar_id' => '5',
                'kode_id' => 'PI',
                'nama' => 'Putus Studi',
                'nilai' => '0',
                'status_semester' => 'N',
                'keluar' => 'Y',
                'status_kembali' => 'Y',
                'def' => 'N',
                'lulus' => 'N',
                'na' => 'N',
                'id_legacy' => 'PSt',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Kosongkan tabel sebelum insert
        DB::table('m_statusmhsw')->truncate();
        
        // Chunk insert untuk performa
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('m_statusmhsw')->insert($chunk);
        }
    }
}