<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class TakategoriSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'ta_kategori_id' => '21',
                'nama' => 'Sistem Informasi Manajemen Basis Data dan Big Data',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '21',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '22',
                'nama' => 'Sistem Informasi Bisnis',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '22',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '23',
                'nama' => 'Sistem Informasi Dalam Segi Keamanan',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '23',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '24',
                'nama' => 'Sistem Informasi Kesehatan',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '24',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '25',
                'nama' => 'Sistem Informasi Pendidikan',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '25',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '26',
                'nama' => 'Sistem Informasi Keuangan',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '26',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '27',
                'nama' => 'Sistem Informasi Logistik dan Manufaktur',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '27',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '28',
                'nama' => 'Sistem Informasi Pemerintahan',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '28',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '29',
                'nama' => 'Sistem Informasi Manajemen Sumber Daya Manusia',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '29',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '30',
                'nama' => 'Sistem Informasi Lingkungan dan Keberlanjutan',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '30',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '31',
                'nama' => 'Sistem Informasi dan Pendidikan',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '31',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '32',
                'nama' => 'Sistem Informasi Koperasi dan Keuangan',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '32',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '33',
                'nama' => 'Sistem Informasi dan Teknologi Pangan',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '33',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '34',
                'nama' => 'Sistem Informasi dan Transportasi',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '34',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '35',
                'nama' => 'Sistem Informasi dan Pariwisata',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '35',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '36',
                'nama' => ' Sistem Informasi Akuntansi',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '36',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '37',
                'nama' => 'Sistem Informasi Berbasis Web',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '37',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '38',
                'nama' => 'Sistem Informasi Penjualan Berbasis Web',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '38',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '39',
                'nama' => 'Sistem Informasi Tanpa Coding',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'Y',
                'id_legacy' => '39',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '40',
                'nama' => ' Sistem Informasi Manajemen',
                'fakultas_id' => 'STMIK',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '40',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '1',
                'nama' => 'Teori Sastra',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '1',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '2',
                'nama' => 'Kritik Sastra',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '2',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '3',
                'nama' => 'Genre Sastra',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '3',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '4',
                'nama' => 'Sastra Bandingan',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '4',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '5',
                'nama' => 'Mitologi Tradisi lisan',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '5',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '6',
                'nama' => 'Seni Tutur',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '6',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '7',
                'nama' => 'Etnografi Visual',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '7',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '8',
                'nama' => 'Semiotika Ruang',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '8',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '9',
                'nama' => 'Semiotika Kuliner',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '9',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '10',
                'nama' => 'Semiotika Desain',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '10',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '11',
                'nama' => 'Pedagogi Sastra',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '11',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '12',
                'nama' => 'Pengembangan Sastra',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '12',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '13',
                'nama' => 'Apresiasi Sastra',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '13',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '14',
                'nama' => 'Sastra dan Kebudayaan',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '14',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '15',
                'nama' => 'Sastra dan Gender',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '15',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '16',
                'nama' => 'Sastra dan Linguistik',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '16',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '17',
                'nama' => 'Sejarah Sastra',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '17',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '18',
                'nama' => 'Teori linguistik',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '18',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '19',
                'nama' => 'Fonetik',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '19',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '20',
                'nama' => 'Fonologi',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '20',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '41',
                'nama' => 'Morfologi',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '41',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '42',
                'nama' => 'Sintaksis',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '42',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '43',
                'nama' => 'Semantik (pragmatik dan semiotik)',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '43',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '44',
                'nama' => 'Analisis wacana',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '44',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '45',
                'nama' => 'Linguistik historis komparatif',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '45',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '46',
                'nama' => 'Pendidikan Bahasa',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '46',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '47',
                'nama' => 'Penterjemahan',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '47',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '48',
                'nama' => 'Psikolinguistisk',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '48',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '49',
                'nama' => 'Sosiolinguistik',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '49',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'ta_kategori_id' => '50',
                'nama' => 'Bahasa dan Budaya',
                'fakultas_id' => 'STBA',
                'prodi_id' => '',
                'na' => 'N',
                'id_legacy' => '50',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Kosongkan tabel sebelum insert
        DB::table('m_takategori')->truncate();
        
        // Chunk insert untuk performa
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('m_takategori')->insert($chunk);
        }
    }
}