<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WarganegaraSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'warga_negara_id' => 'A',
                'nama' => 'United Arab Emirates',
                'na' => 'N',
                'id_legacy' => 'A',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AD',
                'nama' => 'Andorra',
                'na' => 'N',
                'id_legacy' => 'AD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AF',
                'nama' => 'Afghanistan',
                'na' => 'N',
                'id_legacy' => 'AF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AG',
                'nama' => 'Antigua And Barbuda',
                'na' => 'N',
                'id_legacy' => 'AG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AI',
                'nama' => 'Anguilla',
                'na' => 'N',
                'id_legacy' => 'AI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AL',
                'nama' => 'Albania',
                'na' => 'N',
                'id_legacy' => 'AL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AM',
                'nama' => 'Armenia',
                'na' => 'N',
                'id_legacy' => 'AM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AN',
                'nama' => 'Netherlands Antilles',
                'na' => 'N',
                'id_legacy' => 'AN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AO',
                'nama' => 'Angola',
                'na' => 'N',
                'id_legacy' => 'AO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AQ',
                'nama' => 'Antarctica',
                'na' => 'N',
                'id_legacy' => 'AQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AR',
                'nama' => 'Argentina',
                'na' => 'N',
                'id_legacy' => 'AR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AS',
                'nama' => 'American Samoa',
                'na' => 'N',
                'id_legacy' => 'AS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AT',
                'nama' => 'Austria',
                'na' => 'N',
                'id_legacy' => 'AT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AU',
                'nama' => 'Australia',
                'na' => 'N',
                'id_legacy' => 'AU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AW',
                'nama' => 'Aruba',
                'na' => 'N',
                'id_legacy' => 'AW',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AX',
                'nama' => 'Aland Islands',
                'na' => 'N',
                'id_legacy' => 'AX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'AZ',
                'nama' => 'Azerbaijan',
                'na' => 'N',
                'id_legacy' => 'AZ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'B',
                'nama' => 'Belgium',
                'na' => 'N',
                'id_legacy' => 'B',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BA',
                'nama' => 'Bosnia And Herzegovina',
                'na' => 'N',
                'id_legacy' => 'BA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BB',
                'nama' => 'Barbados',
                'na' => 'N',
                'id_legacy' => 'BB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BD',
                'nama' => 'Bangladesh',
                'na' => 'N',
                'id_legacy' => 'BD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BF',
                'nama' => 'Burkina Faso',
                'na' => 'N',
                'id_legacy' => 'BF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BG',
                'nama' => 'Bulgaria',
                'na' => 'N',
                'id_legacy' => 'BG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BH',
                'nama' => 'Bahrain',
                'na' => 'N',
                'id_legacy' => 'BH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BI',
                'nama' => 'Burundi',
                'na' => 'N',
                'id_legacy' => 'BI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BJ',
                'nama' => 'Benin',
                'na' => 'N',
                'id_legacy' => 'BJ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BL',
                'nama' => 'Saint Bartelemey',
                'na' => 'N',
                'id_legacy' => 'BL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BM',
                'nama' => 'Bermuda',
                'na' => 'N',
                'id_legacy' => 'BM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BN',
                'nama' => 'Brunei Darussalam',
                'na' => 'N',
                'id_legacy' => 'BN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BO',
                'nama' => 'Bolivia',
                'na' => 'N',
                'id_legacy' => 'BO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BQ',
                'nama' => 'Bonaire, Saint Eustatius and Saba',
                'na' => 'N',
                'id_legacy' => 'BQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BR',
                'nama' => 'Brazil',
                'na' => 'N',
                'id_legacy' => 'BR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BS',
                'nama' => 'Bahamas',
                'na' => 'N',
                'id_legacy' => 'BS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BT',
                'nama' => 'Bhutan',
                'na' => 'N',
                'id_legacy' => 'BT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BV',
                'nama' => 'Bouvet Island',
                'na' => 'N',
                'id_legacy' => 'BV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BW',
                'nama' => 'Botswana',
                'na' => 'N',
                'id_legacy' => 'BW',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BY',
                'nama' => 'Belarus',
                'na' => 'N',
                'id_legacy' => 'BY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'BZ',
                'nama' => 'Belize',
                'na' => 'N',
                'id_legacy' => 'BZ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CA',
                'nama' => 'Canada',
                'na' => 'N',
                'id_legacy' => 'CA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CC',
                'nama' => 'Cocos (Keeling) Islands',
                'na' => 'N',
                'id_legacy' => 'CC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CD',
                'nama' => 'Congo, The Democratic Republic Of The',
                'na' => 'N',
                'id_legacy' => 'CD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CF',
                'nama' => 'Central African Republic',
                'na' => 'N',
                'id_legacy' => 'CF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CG',
                'nama' => 'Congo',
                'na' => 'N',
                'id_legacy' => 'CG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CH',
                'nama' => 'Switzerland',
                'na' => 'N',
                'id_legacy' => 'CH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CI',
                'nama' => 'Cote D\'Ivoire',
                'na' => 'N',
                'id_legacy' => 'CI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CK',
                'nama' => 'Cook Islands',
                'na' => 'N',
                'id_legacy' => 'CK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CL',
                'nama' => 'Chile',
                'na' => 'N',
                'id_legacy' => 'CL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CM',
                'nama' => 'Cameroon',
                'na' => 'N',
                'id_legacy' => 'CM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CN',
                'nama' => 'China',
                'na' => 'N',
                'id_legacy' => 'CN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CO',
                'nama' => 'Colombia',
                'na' => 'N',
                'id_legacy' => 'CO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CR',
                'nama' => 'Costa Rica',
                'na' => 'N',
                'id_legacy' => 'CR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CS',
                'nama' => 'Serbia And Montenegro',
                'na' => 'N',
                'id_legacy' => 'CS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CU',
                'nama' => 'Cuba',
                'na' => 'N',
                'id_legacy' => 'CU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CV',
                'nama' => 'Cape Verde',
                'na' => 'N',
                'id_legacy' => 'CV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CW',
                'nama' => 'Curacao',
                'na' => 'N',
                'id_legacy' => 'CW',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CX',
                'nama' => 'Christmas Island',
                'na' => 'N',
                'id_legacy' => 'CX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CY',
                'nama' => 'Cyprus',
                'na' => 'N',
                'id_legacy' => 'CY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'CZ',
                'nama' => 'Czech Republic',
                'na' => 'N',
                'id_legacy' => 'CZ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'D',
                'nama' => 'Germany',
                'na' => 'N',
                'id_legacy' => 'D',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'DJ',
                'nama' => 'Djibouti',
                'na' => 'N',
                'id_legacy' => 'DJ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'DK',
                'nama' => 'Denmark',
                'na' => 'N',
                'id_legacy' => 'DK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'DM',
                'nama' => 'Dominica',
                'na' => 'N',
                'id_legacy' => 'DM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'DO',
                'nama' => 'Dominican Republic',
                'na' => 'N',
                'id_legacy' => 'DO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'DZ',
                'nama' => 'Algeria',
                'na' => 'N',
                'id_legacy' => 'DZ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'E',
                'nama' => 'Estonia',
                'na' => 'N',
                'id_legacy' => 'E',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'EC',
                'nama' => 'Ecuador',
                'na' => 'N',
                'id_legacy' => 'EC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'EG',
                'nama' => 'Egypt',
                'na' => 'N',
                'id_legacy' => 'EG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'EH',
                'nama' => 'Western Sahara',
                'na' => 'N',
                'id_legacy' => 'EH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'ER',
                'nama' => 'Eritrea',
                'na' => 'N',
                'id_legacy' => 'ER',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'ES',
                'nama' => 'Spain',
                'na' => 'N',
                'id_legacy' => 'ES',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'ET',
                'nama' => 'Ethiopia',
                'na' => 'N',
                'id_legacy' => 'ET',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'FI',
                'nama' => 'Finland',
                'na' => 'N',
                'id_legacy' => 'FI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'FJ',
                'nama' => 'Fiji',
                'na' => 'N',
                'id_legacy' => 'FJ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'FK',
                'nama' => 'Falkland Islands (Malvinas)',
                'na' => 'N',
                'id_legacy' => 'FK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'FM',
                'nama' => 'Micronesia, Federated States Of',
                'na' => 'N',
                'id_legacy' => 'FM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'FO',
                'nama' => 'Faroe Islands',
                'na' => 'N',
                'id_legacy' => 'FO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'FR',
                'nama' => 'France',
                'na' => 'N',
                'id_legacy' => 'FR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'G',
                'nama' => 'Georgia',
                'na' => 'N',
                'id_legacy' => 'G',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GA',
                'nama' => 'Gabon',
                'na' => 'N',
                'id_legacy' => 'GA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GB',
                'nama' => 'United Kingdom',
                'na' => 'N',
                'id_legacy' => 'GB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GD',
                'nama' => 'Grenada',
                'na' => 'N',
                'id_legacy' => 'GD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GF',
                'nama' => 'French Guiana',
                'na' => 'N',
                'id_legacy' => 'GF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GG',
                'nama' => 'Guernsey',
                'na' => 'N',
                'id_legacy' => 'GG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GH',
                'nama' => 'Ghana',
                'na' => 'N',
                'id_legacy' => 'GH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GI',
                'nama' => 'Gibraltar',
                'na' => 'N',
                'id_legacy' => 'GI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GL',
                'nama' => 'Greenland',
                'na' => 'N',
                'id_legacy' => 'GL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GM',
                'nama' => 'Gambia',
                'na' => 'N',
                'id_legacy' => 'GM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GN',
                'nama' => 'Guinea',
                'na' => 'N',
                'id_legacy' => 'GN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GP',
                'nama' => 'Guadeloupe',
                'na' => 'N',
                'id_legacy' => 'GP',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GQ',
                'nama' => 'Equatorial Guinea',
                'na' => 'N',
                'id_legacy' => 'GQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GR',
                'nama' => 'Greece',
                'na' => 'N',
                'id_legacy' => 'GR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GS',
                'nama' => 'South Georgia And The South Sandwich Islands',
                'na' => 'N',
                'id_legacy' => 'GS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GT',
                'nama' => 'Guatemala',
                'na' => 'N',
                'id_legacy' => 'GT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GU',
                'nama' => 'Guam',
                'na' => 'N',
                'id_legacy' => 'GU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GW',
                'nama' => 'Guinea-Bissau',
                'na' => 'N',
                'id_legacy' => 'GW',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'GY',
                'nama' => 'Guyana',
                'na' => 'N',
                'id_legacy' => 'GY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'HK',
                'nama' => 'Hong Kong',
                'na' => 'N',
                'id_legacy' => 'HK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'HM',
                'nama' => 'Heard Island And Mcdonald Islands',
                'na' => 'N',
                'id_legacy' => 'HM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'HN',
                'nama' => 'Honduras',
                'na' => 'N',
                'id_legacy' => 'HN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'HR',
                'nama' => 'Croatia',
                'na' => 'N',
                'id_legacy' => 'HR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'HT',
                'nama' => 'Haiti',
                'na' => 'N',
                'id_legacy' => 'HT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'HU',
                'nama' => 'Hungary',
                'na' => 'N',
                'id_legacy' => 'HU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'I',
                'nama' => 'Ireland',
                'na' => 'N',
                'id_legacy' => 'I',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'ID',
                'nama' => 'Indonesia                     ',
                'na' => 'N',
                'id_legacy' => 'ID',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'IL',
                'nama' => 'Israel',
                'na' => 'N',
                'id_legacy' => 'IL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'IM',
                'nama' => 'Isle Of Man',
                'na' => 'N',
                'id_legacy' => 'IM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'IN',
                'nama' => 'India',
                'na' => 'N',
                'id_legacy' => 'IN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'IO',
                'nama' => 'British Indian Ocean Territory',
                'na' => 'N',
                'id_legacy' => 'IO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'IQ',
                'nama' => 'Iraq',
                'na' => 'N',
                'id_legacy' => 'IQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'IR',
                'nama' => 'Iran, Islamic Republic Of',
                'na' => 'N',
                'id_legacy' => 'IR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'IS',
                'nama' => 'Iceland',
                'na' => 'N',
                'id_legacy' => 'IS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'IT',
                'nama' => 'Italy',
                'na' => 'N',
                'id_legacy' => 'IT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'J',
                'nama' => 'Jersey',
                'na' => 'N',
                'id_legacy' => 'J',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'JM',
                'nama' => 'Jamaica',
                'na' => 'N',
                'id_legacy' => 'JM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'JO',
                'nama' => 'Jordan',
                'na' => 'N',
                'id_legacy' => 'JO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'JP',
                'nama' => 'Japan',
                'na' => 'N',
                'id_legacy' => 'JP',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'K',
                'nama' => 'Kenya',
                'na' => 'N',
                'id_legacy' => 'K',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'KG',
                'nama' => 'Kyrgyzstan',
                'na' => 'N',
                'id_legacy' => 'KG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'KH',
                'nama' => 'Cambodia',
                'na' => 'N',
                'id_legacy' => 'KH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'KI',
                'nama' => 'Kiribati',
                'na' => 'N',
                'id_legacy' => 'KI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'KM',
                'nama' => 'Comoros',
                'na' => 'N',
                'id_legacy' => 'KM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'KN',
                'nama' => 'Saint Kitts And Nevis',
                'na' => 'N',
                'id_legacy' => 'KN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'KP',
                'nama' => 'Korea, Democratic People\'S Republic Of',
                'na' => 'N',
                'id_legacy' => 'KP',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'KR',
                'nama' => 'Korea, Republic Of',
                'na' => 'N',
                'id_legacy' => 'KR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'KW',
                'nama' => 'Kuwait',
                'na' => 'N',
                'id_legacy' => 'KW',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'KY',
                'nama' => 'Cayman Islands',
                'na' => 'N',
                'id_legacy' => 'KY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'KZ',
                'nama' => 'Kazakhstan',
                'na' => 'N',
                'id_legacy' => 'KZ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LA',
                'nama' => 'Lao People\'S Democratic Republic',
                'na' => 'N',
                'id_legacy' => 'LA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LB',
                'nama' => 'Lebanon',
                'na' => 'N',
                'id_legacy' => 'LB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LC',
                'nama' => 'Saint Lucia',
                'na' => 'N',
                'id_legacy' => 'LC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LI',
                'nama' => 'Liechtenstein',
                'na' => 'N',
                'id_legacy' => 'LI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LK',
                'nama' => 'Sri Lanka',
                'na' => 'N',
                'id_legacy' => 'LK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LR',
                'nama' => 'Liberia',
                'na' => 'N',
                'id_legacy' => 'LR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LS',
                'nama' => 'Lesotho',
                'na' => 'N',
                'id_legacy' => 'LS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LT',
                'nama' => 'Lithuania',
                'na' => 'N',
                'id_legacy' => 'LT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LU',
                'nama' => 'Luxembourg',
                'na' => 'N',
                'id_legacy' => 'LU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LV',
                'nama' => 'Latvia',
                'na' => 'N',
                'id_legacy' => 'LV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'LY',
                'nama' => 'Libyan Arab Jamahiriya',
                'na' => 'N',
                'id_legacy' => 'LY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'M',
                'nama' => 'Montenegro',
                'na' => 'N',
                'id_legacy' => 'M',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MA',
                'nama' => 'Morocco',
                'na' => 'N',
                'id_legacy' => 'MA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MC',
                'nama' => 'Monaco',
                'na' => 'N',
                'id_legacy' => 'MC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MD',
                'nama' => 'Moldova, Republic Of',
                'na' => 'N',
                'id_legacy' => 'MD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MF',
                'nama' => 'Saint Martin',
                'na' => 'N',
                'id_legacy' => 'MF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MG',
                'nama' => 'Madagascar',
                'na' => 'N',
                'id_legacy' => 'MG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MH',
                'nama' => 'Marshall Islands',
                'na' => 'N',
                'id_legacy' => 'MH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MK',
                'nama' => 'Macedonia, The Former Yugoslav Republic Of',
                'na' => 'N',
                'id_legacy' => 'MK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'ML',
                'nama' => 'Mali',
                'na' => 'N',
                'id_legacy' => 'ML',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MM',
                'nama' => 'Myanmar',
                'na' => 'N',
                'id_legacy' => 'MM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MN',
                'nama' => 'Mongolia',
                'na' => 'N',
                'id_legacy' => 'MN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MO',
                'nama' => 'Macao',
                'na' => 'N',
                'id_legacy' => 'MO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MP',
                'nama' => 'Northern Mariana Islands',
                'na' => 'N',
                'id_legacy' => 'MP',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MQ',
                'nama' => 'Martinique',
                'na' => 'N',
                'id_legacy' => 'MQ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MR',
                'nama' => 'Mauritania',
                'na' => 'N',
                'id_legacy' => 'MR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MS',
                'nama' => 'Montserrat',
                'na' => 'N',
                'id_legacy' => 'MS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MT',
                'nama' => 'Malta',
                'na' => 'N',
                'id_legacy' => 'MT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MU',
                'nama' => 'Mauritius',
                'na' => 'N',
                'id_legacy' => 'MU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MV',
                'nama' => 'Maldives',
                'na' => 'N',
                'id_legacy' => 'MV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MW',
                'nama' => 'Malawi',
                'na' => 'N',
                'id_legacy' => 'MW',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MX',
                'nama' => 'Mexico',
                'na' => 'N',
                'id_legacy' => 'MX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MY',
                'nama' => 'Malaysia',
                'na' => 'N',
                'id_legacy' => 'MY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'MZ',
                'nama' => 'Mozambique',
                'na' => 'N',
                'id_legacy' => 'MZ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'N',
                'nama' => 'Niger',
                'na' => 'N',
                'id_legacy' => 'N',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NA',
                'nama' => 'Namibia',
                'na' => 'N',
                'id_legacy' => 'NA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NC',
                'nama' => 'New Caledonia',
                'na' => 'N',
                'id_legacy' => 'NC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NF',
                'nama' => 'Norfolk Island',
                'na' => 'N',
                'id_legacy' => 'NF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NG',
                'nama' => 'Nigeria',
                'na' => 'N',
                'id_legacy' => 'NG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NI',
                'nama' => 'Nicaragua',
                'na' => 'N',
                'id_legacy' => 'NI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NL',
                'nama' => 'Netherlands',
                'na' => 'N',
                'id_legacy' => 'NL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NO',
                'nama' => 'Norway',
                'na' => 'N',
                'id_legacy' => 'NO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NP',
                'nama' => 'Nepal',
                'na' => 'N',
                'id_legacy' => 'NP',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NR',
                'nama' => 'Nauru',
                'na' => 'N',
                'id_legacy' => 'NR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NU',
                'nama' => 'Niue',
                'na' => 'N',
                'id_legacy' => 'NU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'NZ',
                'nama' => 'New Zealand',
                'na' => 'N',
                'id_legacy' => 'NZ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'OM',
                'nama' => 'Oman',
                'na' => 'N',
                'id_legacy' => 'OM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'P',
                'nama' => 'Peru',
                'na' => 'N',
                'id_legacy' => 'P',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PA',
                'nama' => 'Panama',
                'na' => 'N',
                'id_legacy' => 'PA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PF',
                'nama' => 'French Polynesia',
                'na' => 'N',
                'id_legacy' => 'PF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PG',
                'nama' => 'Papua New Guinea',
                'na' => 'N',
                'id_legacy' => 'PG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PH',
                'nama' => 'Philippines',
                'na' => 'N',
                'id_legacy' => 'PH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PK',
                'nama' => 'Pakistan',
                'na' => 'N',
                'id_legacy' => 'PK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PL',
                'nama' => 'Poland',
                'na' => 'N',
                'id_legacy' => 'PL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PM',
                'nama' => 'Saint Pierre And Miquelon',
                'na' => 'N',
                'id_legacy' => 'PM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PN',
                'nama' => 'Pitcairn',
                'na' => 'N',
                'id_legacy' => 'PN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PR',
                'nama' => 'Puerto Rico',
                'na' => 'N',
                'id_legacy' => 'PR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PS',
                'nama' => 'Palestinian Territory, Occupied',
                'na' => 'N',
                'id_legacy' => 'PS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PT',
                'nama' => 'Portugal',
                'na' => 'N',
                'id_legacy' => 'PT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PW',
                'nama' => 'Palau',
                'na' => 'N',
                'id_legacy' => 'PW',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'PY',
                'nama' => 'Paraguay',
                'na' => 'N',
                'id_legacy' => 'PY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'QA',
                'nama' => 'Qatar',
                'na' => 'N',
                'id_legacy' => 'QA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'R',
                'nama' => 'Reunion',
                'na' => 'N',
                'id_legacy' => 'R',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'RO',
                'nama' => 'Romania',
                'na' => 'N',
                'id_legacy' => 'RO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'RS',
                'nama' => 'Serbia',
                'na' => 'N',
                'id_legacy' => 'RS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'RU',
                'nama' => 'Russian Federation',
                'na' => 'N',
                'id_legacy' => 'RU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'RW',
                'nama' => 'Rwanda',
                'na' => 'N',
                'id_legacy' => 'RW',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'S',
                'nama' => 'Sweden',
                'na' => 'N',
                'id_legacy' => 'S',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SA',
                'nama' => 'Saudi Arabia',
                'na' => 'N',
                'id_legacy' => 'SA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SB',
                'nama' => 'Solomon Islands',
                'na' => 'N',
                'id_legacy' => 'SB',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SC',
                'nama' => 'Seychelles',
                'na' => 'N',
                'id_legacy' => 'SC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SD',
                'nama' => 'Sudan',
                'na' => 'N',
                'id_legacy' => 'SD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SG',
                'nama' => 'Singapore',
                'na' => 'N',
                'id_legacy' => 'SG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SH',
                'nama' => 'Saint Helena',
                'na' => 'N',
                'id_legacy' => 'SH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SI',
                'nama' => 'Slovenia',
                'na' => 'N',
                'id_legacy' => 'SI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SJ',
                'nama' => 'Svalbard And Jan Mayen',
                'na' => 'N',
                'id_legacy' => 'SJ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SK',
                'nama' => 'Slovakia',
                'na' => 'N',
                'id_legacy' => 'SK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SL',
                'nama' => 'Sierra Leone',
                'na' => 'N',
                'id_legacy' => 'SL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SM',
                'nama' => 'San Marino',
                'na' => 'N',
                'id_legacy' => 'SM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SN',
                'nama' => 'Senegal',
                'na' => 'N',
                'id_legacy' => 'SN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SO',
                'nama' => 'Somalia',
                'na' => 'N',
                'id_legacy' => 'SO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SR',
                'nama' => 'Suriname',
                'na' => 'N',
                'id_legacy' => 'SR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SS',
                'nama' => 'South Sudan',
                'na' => 'N',
                'id_legacy' => 'SS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'ST',
                'nama' => 'Sao Tome And Principe',
                'na' => 'N',
                'id_legacy' => 'ST',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SV',
                'nama' => 'El Salvador',
                'na' => 'N',
                'id_legacy' => 'SV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SX',
                'nama' => 'Sint Maarten',
                'na' => 'N',
                'id_legacy' => 'SX',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SY',
                'nama' => 'Syrian Arab Republic',
                'na' => 'N',
                'id_legacy' => 'SY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'SZ',
                'nama' => 'Swaziland',
                'na' => 'N',
                'id_legacy' => 'SZ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TC',
                'nama' => 'Turks And Caicos Islands',
                'na' => 'N',
                'id_legacy' => 'TC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TD',
                'nama' => 'Chad',
                'na' => 'N',
                'id_legacy' => 'TD',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TF',
                'nama' => 'French Southern Territories',
                'na' => 'N',
                'id_legacy' => 'TF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TG',
                'nama' => 'Togo',
                'na' => 'N',
                'id_legacy' => 'TG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TH',
                'nama' => 'Thailand',
                'na' => 'N',
                'id_legacy' => 'TH',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TJ',
                'nama' => 'Tajikistan',
                'na' => 'N',
                'id_legacy' => 'TJ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TK',
                'nama' => 'Tokelau',
                'na' => 'N',
                'id_legacy' => 'TK',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TL',
                'nama' => 'Timor-Leste',
                'na' => 'N',
                'id_legacy' => 'TL',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TM',
                'nama' => 'Turkmenistan',
                'na' => 'N',
                'id_legacy' => 'TM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TN',
                'nama' => 'Tunisia',
                'na' => 'N',
                'id_legacy' => 'TN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TO',
                'nama' => 'Tonga',
                'na' => 'N',
                'id_legacy' => 'TO',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TR',
                'nama' => 'Turkey',
                'na' => 'N',
                'id_legacy' => 'TR',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TT',
                'nama' => 'Trinidad And Tobago',
                'na' => 'N',
                'id_legacy' => 'TT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TV',
                'nama' => 'Tuvalu',
                'na' => 'N',
                'id_legacy' => 'TV',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TW',
                'nama' => 'Taiwan, Province Of China',
                'na' => 'N',
                'id_legacy' => 'TW',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'TZ',
                'nama' => 'Tanzania, United Republic Of',
                'na' => 'N',
                'id_legacy' => 'TZ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'UA',
                'nama' => 'Ukraine',
                'na' => 'N',
                'id_legacy' => 'UA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'UG',
                'nama' => 'Uganda',
                'na' => 'N',
                'id_legacy' => 'UG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'UM',
                'nama' => 'United States Minor Outlying Islands',
                'na' => 'N',
                'id_legacy' => 'UM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'US',
                'nama' => 'United States',
                'na' => 'N',
                'id_legacy' => 'US',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'UY',
                'nama' => 'Uruguay',
                'na' => 'N',
                'id_legacy' => 'UY',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'UZ',
                'nama' => 'Uzbekistan',
                'na' => 'N',
                'id_legacy' => 'UZ',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'V',
                'nama' => 'Venezuela',
                'na' => 'N',
                'id_legacy' => 'V',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'VA',
                'nama' => 'Holy See (Vatican City State)',
                'na' => 'N',
                'id_legacy' => 'VA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'VC',
                'nama' => 'Saint Vincent And The Grenadines',
                'na' => 'N',
                'id_legacy' => 'VC',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'VG',
                'nama' => 'Virgin Islands, British',
                'na' => 'N',
                'id_legacy' => 'VG',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'VI',
                'nama' => 'Virgin Islands, U.S.',
                'na' => 'N',
                'id_legacy' => 'VI',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'VN',
                'nama' => 'Viet Nam',
                'na' => 'N',
                'id_legacy' => 'VN',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'VU',
                'nama' => 'Vanuatu',
                'na' => 'N',
                'id_legacy' => 'VU',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'WF',
                'nama' => 'Wallis And Futuna',
                'na' => 'N',
                'id_legacy' => 'WF',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'WS',
                'nama' => 'Samoa',
                'na' => 'N',
                'id_legacy' => 'WS',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'Y',
                'nama' => 'Yemen',
                'na' => 'N',
                'id_legacy' => 'Y',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'YT',
                'nama' => 'Mayotte',
                'na' => 'N',
                'id_legacy' => 'YT',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'ZA',
                'nama' => 'South Africa',
                'na' => 'N',
                'id_legacy' => 'ZA',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'ZM',
                'nama' => 'Zambia',
                'na' => 'N',
                'id_legacy' => 'ZM',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'warga_negara_id' => 'ZW',
                'nama' => 'Zimbabwe',
                'na' => 'N',
                'id_legacy' => 'ZW',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ];

        // Kosongkan tabel sebelum insert
        DB::table('m_warganegara')->truncate();
        
        // Chunk insert untuk performa
        foreach (array_chunk($data, 100) as $chunk) {
            DB::table('m_warganegara')->insert($chunk);
        }
    }
}