<?php

// Variables
return [
    'creatorName' => 'imam-starter-kit team',
    'creatorUrl' => 'https://github.com/imamzaenuddin/',
    'templateName' => 'imam-starter-kit',
    'templateSuffix' => 'Laravel Livewire Volt Starter Kit',
    'templateVersion' => '1.0.1',
    'templateFree' => true,
    'templateDescription' => 'imam-starter-kit berbasis Laravel 12, Livewire Volt, dan Bootstrap 5.',
    'templateKeyword' => 'imam starter kit, laravel 12, livewire volt, bootstrap 5, dashboard organisasi',
    'licenseUrl' => 'https://github.com/imamzaenuddin/imam-starter-kit/blob/main/LICENSE',
    'livePreview' => 'https://github.com/imamzaenuddin/imam-starter-kit',
    'productPage' => 'https://github.com/imamzaenuddin/imam-starter-kit',
    'ogTitle' => 'imam-starter-kit',
    'ogType' => 'product',
    'ogImage' => 'https://github-production-user-asset-6210df.s3.amazonaws.com/61959920/427962312-a4f2c59c-92a0-4624-a0f0-d53ee0acf7d9.png?X-Amz-Algorithm=AWS4-HMAC-SHA256&X-Amz-Credential=AKIAVCODYLSA53PQK4ZA%2F20250328%2Fus-east-1%2Fs3%2Faws4_request&X-Amz-Date=20250328T104541Z&X-Amz-Expires=300&X-Amz-Signature=88f19338f62219496631c44f4da216a3f2da10169fb75377cdc9146dc1722352&X-Amz-SignedHeaders=host',
    'support' => 'https://github.com/imamzaenuddin/imam-starter-kit/issues',
    'moreThemes' => 'https://github.com/imamzaenuddin/',
    'documentation' => 'https://github.com/imamzaenuddin/imam-starter-kit/blob/main/README.md',
    'repository' => 'https://github.com/imamzaenuddin/imam-starter-kit',
    'gitRepo' => 'https://github.com/imamzaenuddin/imam-starter-kit.git',
    'gitRepoAccess' => 'https://github.com/imamzaenuddin/',
    'githubFreeUrl' => 'https://github.com/imamzaenuddin/',
    'facebookUrl' => 'https://github.com/imamzaenuddin/',
    'twitterUrl' => 'https://github.com/imamzaenuddin/',
    'githubUrl' => 'https://github.com/imamzaenuddin/',
    'dribbbleUrl' => 'https://github.com/imamzaenuddin/',
    'instagramUrl' => 'https://github.com/imamzaenuddin/',
];
